### ISSUE TITLE
Problem with requirejs and urlArgs

### ISSUE THREAD

**Issue by NikitaEgorov** [mmanela/chutzpah#309]
Coverage not work: "Illegal characters in path."

 at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
   at System.IO.File.ReadAllLines(String path)
   at Chutzpah.Wrappers.FileSystemWrapper.GetLines(String path) in \chutzpah-master\Chutzpah\Wrappers\FileSystemWrapper.cs:line 162
   at Chutzpah.Coverage.BlanketJsCoverageEngine.DeserializeCoverageObject(String json, TestContext testContext) in chutzpah-master\Chutzpah\Coverage\BlanketJsCoverageEngine.cs:line 148
   at Chutzpah.TestCaseStreamReader.ReadFromStream(StreamReader stream, TestContext testContext, TestOptions testOptions, ITestMethodRunnerCallback callback, Boolean debugEnabled) in chutzpah-master\Chutzpah\TestCaseStreamReader.cs:line 114
   at Chutzpah.TestCaseStreamReader.<>c__DisplayClass1.<Read>b__0() in chutzpah-master\Chutzpah\TestCaseStreamReader.cs:line 48
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Chutzpah.TestCaseStreamReader.Read(ProcessStream processStream, TestOptions testOptions, TestContext testContext, ITestMethodRunnerCallback callback, Boolean debugEnabled) in chutzpah-master\Chutzpah\TestCaseStreamReader.cs:line 58
   at Chutzpah.TestRunner.<>c__DisplayClassc.<InvokeTestRunner>b__b(ProcessStream processStream) in chutzpah-master\Chutzpah\TestRunner.cs:line 439
   at Chutzpah.ProcessHelper.RunExecutableAndProcessOutput[T](String exePath, String arguments, Func`2 streamProcessor) in chutzpah-master\Chutzpah\ProcessHelper.cs:line 27
   at Chutzpah.TestRunner.InvokeTestRunner(String headlessBrowserPath, TestOptions options, TestContext testContext, TestExecutionMode testExecutionMode, ITestMethodRunnerCallback callback) in chutzpah-master\Chutzpah\TestRunner.cs:line 440
   at Chutzpah.TestRunner.<>c__DisplayClass3.<ExecuteTestContexts>b__2(TestContext testContext) in chutzpah-master\Chutzpah\TestRunner.cs:line 278
---> (Inner Exception #0) System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
   at System.IO.File.ReadAllLines(String path)
   at Chutzpah.Wrappers.FileSystemWrapper.GetLines(String path) in chutzpah-master\Chutzpah\Wrappers\FileSystemWrapper.cs:line 162
   at Chutzpah.Coverage.BlanketJsCoverageEngine.DeserializeCoverageObject(String json, TestContext testContext) in chutzpah-master\Chutzpah\Coverage\BlanketJsCoverageEngine.cs:line 148
   at Chutzpah.TestCaseStreamReader.ReadFromStream(StreamReader stream, TestContext testContext, TestOptions testOptions, ITestMethodRunnerCallback callback, Boolean debugEnabled) in chutzpah-master\Chutzpah\TestCaseStreamReader.cs:line 114
   at Chutzpah.TestCaseStreamReader.<>c__DisplayClass1.<Read>b__0() in chutzpah-master\Chutzpah\TestCaseStreamReader.cs:line 48
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

I fixed this problem like this:
BlanketJsCoverageEngine.cs

  filePath = RegexPatterns.InvalidPrefixedLocalFilePath.Replace(filePath, "$1");

>>//REMOVE Query part of filepath like ?ver=1233123
>>filePath = Regex.Replace(filePath, @"(.*)\?.*", "$1", RegexOptions.IgnoreCase);

var fileUri = new Uri(filePath, UriKind.RelativeOrAbsolute);

**Comment by NikitaEgorov** [comment]
Yes, I try
