### ISSUE TITLE
Unable to discover tests after Chutzpah upgrade from 3.3.1 to 4.1.0

### ISSUE THREAD

**Issue by IEvangelist** [mmanela/chutzpah#422]
While using version 3.3.1 chutzpah was able to discover all desired jasmine unit tests as expected. After upgrading to version 4.1.0 no tests are found. The chutzpah.json files have been created, but none of the tests are still being discovered. What could be missing?

The project is structured like so:

<pre>
+-- Root
|  +-- Client
|  |  +-- js
|  |  |  +-- app
|  |  |  |  +-- reporting
|  |  |  |  |  ReportingController.ts
|  +-- Tests
|  |  +-- app
|  |  |  +-- reporting
|  |  |  |  ReportingControllerTests.ts
|  chutzpah.json
</pre>

Here is the chutzpah.json file contents.
```json
{
    "Framework": "jasmine",
    "TestFileTimeout": "60000",
    "TestHarnessReferenceMode": "AMD",
    "TestHarnessLocationMode": "SettingsFileAdjacent",
    "EnableTestFileBatching": true,
    "Tests": [
        { "Path": [ "tests" ] }
    ]
}
```
Output from Tests shows:
<pre>
------ Discover test started ------
========== Discover test finished: 0 found (0:00:00.9760976) ==========
</pre>

I can send you a zip file with the source if you need to see it. Putting it on GitHub will take a lot of paperwork on my part for my boss.

**Comment by mmanela** [comment]
Chutzpah no longer compiles your typescript files for you. You must use the [compile setting](https://github.com/mmanela/chutzpah/wiki/Compile-Setting) to tell Chutzpah how to handle those files.

**Comment by guyjci** [comment]
I'm working with the OP on this issue internally. 
We've tried changing the chutzpah.json file to the following and still get "Error: Timeout occurred when executing test file" Both when having Visual Studio find the tests and when using the Context Menu - Run JS Tests.

Here is the new chutzpah.json file.
```
{
    "Framework": "jasmine",
    "TestFileTimeout": "60000",
    "ExpandReferenceComments": "false",
    "Compile": {
        "Mode": "External",
        "Extensions": [ ".ts" ],
        "ExtensionsWithNoOutput": [ ".d.ts" ],
        "SourceDirectory": "tests",
        "OutDirectory": "../Eos.OperationalTool.UI/"
    },
    "Tests": [
        { "Includes": [ "*/tests/*.ts" ], "Excludes": [ "*/tests/*.d.ts", "*/TestingIncludes.ts" ] }
    ]
}
```
Any suggestions? 
Not sure if this matters, but, I do notice that the _Chutzpah*.test.html file in the OutDirectory has a "No specs found" message.

**Comment by mmanela** [comment]
What is compiling your tests? Did you set up VS to do it?

**Comment by guyjci** [comment]
Yes, we have "compile on save" setup. The tests are in the OutDirectory as *.js files.

**Comment by mmanela** [comment]
Couple things 
1. Try to run with the /trace flag and chutzpah will generate a log file telling you what it is trying to do.
2. Examine the HTML file chutzpah generates to see what it is missing or getting wrong.

**Comment by guyjci** [comment]
Here is the command line I run
```
chutzpah.console /Tests/app/reporting/ReportingServiceTsts.ts /trace
```
Here is the log file results 
```
chutzpah.console Information: 0 : Time:10:22:52.6459847; Thread:1; Message:Chutzpah run started in mode Execution with parallelism set to 8
chutzpah.console Information: 0 : Time:10:22:52.6609847; Thread:1; Message:Using Chutzpah.json files to find tests
chutzpah.console Information: 0 : Time:10:22:52.6709847; Thread:1; Message:Chutzpah.json file cache cleared
chutzpah.console Information: 0 : Time:10:22:52.6719847; Thread:1; Message:Chutzpah run finished with 0 passed, 0 failed and 0 errors
```
Running from the command line - I do not get an html file.

**Comment by mmanela** [comment]
Run using the /debug flag and show me the output and you should be able to see the .html then too.

**Comment by guyjci** [comment]
It appears to be a pathing issue of some sort in the chutzpah.json - as now I get an html file with an error saying:
```
TypeError: Reporting.ReportingController is not a function.
```
Here is the actual html if that helps. 
```
Jasmine2.0.0finished in 0.024s
raise exceptions
1 spec, 1 failure
Spec List | Failures
ReportingController constructor should initialize data
TypeError: Reporting.ReportingController is not a function
TypeError: Reporting.ReportingController is not a function
    at Object.<anonymous> (file:///C:/JUNK/src/Eos.OperationalTool.UI/Tests/app/Reporting/ReportingControllerTests.js:30:43)
    at attemptSync (file:///C:/Users/cstolpm/Documents/Eos.Testing.Chutzpah/Chutzpah/TestFiles/jasmine/v2/jasmine.js:1510:12)
    at QueueRunner.run (file:///C:/Users/cstolpm/Documents/Eos.Testing.Chutzpah/Chutzpah/TestFiles/jasmine/v2/jasmine.js:1498:9)
    at QueueRunner.execute (file:///C:/Users/cstolpm/Documents/Eos.Testing.Chutzpah/Chutzpah/TestFiles/jasmine/v2/jasmine.js:1485:10)
    at Spec.Env.queueRunnerFactory (file:///C:/Users/cstolpm/Documents/Eos.Testing.Chutzpah/Chutzpah/TestFiles/jasmine/v2/jasmine.js:518:35)
    at Spec.execute (file:///C:/Users/cstolpm/Documents/Eos.Testing.Chutzpah/Chutzpah/TestFiles/jasmine/v2/jasmine.js:306:10)
    at Object.<anonymous> (file:///C:/Users/cstolpm/Documents/Eos.Testing.Chutzpah/Chutzpah/TestFiles/jasmine/v2/jasmine.js:1708:37)
    at attemptAsync (file:///C:/Users/cstolpm/Documents/Eos.Testing.Chutzpah/Chutzpah/TestFiles/jasmine/v2/jasmine.js:1520:12)
    at QueueRunner.run (file:///C:/Users/cstolpm/Documents/Eos.Testing.Chutzpah/Chutzpah/TestFiles/jasmine/v2/jasmine.js:1496:16)
    at QueueRunner.execute (file:///C:/Users/cstolpm/Documents/Eos.Testing.Chutzpah/Chutzpah/TestFiles/jasmine/v2/jasmine.js:1485:10)
```

I have made several changes to the chutzpah.json file that have seemed to help - but this one is still stumping me. Here's the new chutzpah.json.
```
{
    "Framework": "jasmine",
    "TestFileTimeout": "60000",

    "ExpandReferenceComments": "true",
    "Compile": {
        "Mode": "External",
        "Extensions": [ ".ts" ],
        "SourceDirectory": "tests",
        "OutDirectory": "../Eos.OperationalTool.UI/Tests/"

    },
    "Tests": [
        { "Includes": [ "*/tests/*/*.ts" ], "Excludes": [ "*/tests/*.d.ts", "*/scripts/*/*.js" ] }
    ],
    "References": [
        { "Include": "*/scripts/angular.js" },
        { "Include": "*/scripts/angular-route.js" },
        { "Include": "*/scripts/angular-mocks.js" },
        { "Include": "../client/js/app/EosApp.js" },
        { "Include": "../client/js/app/reporting/ReportingController.js"},
        { "Include": "../client/js/app/*"}

    ],

    "CodeCoverageExcludes": [ "*angular*.js", "*lodash*.js", "*moment*.js", "*tests*.ts", "*/interfaces/*.ts", "*highstock.js", "*jquery-2.1.0.js" ],
    "EnableCodeCoverage": "false"
}
```

**Comment by guyjci** [comment]
So it seems to have boiled down to pathing issues for the most part.
We use a custom TypeScript Build Output folder - so I needed to change the OutDirectory to match that path. So the new Chutzpah.json looks like this.
```
{
    "Framework": "jasmine",
    "TestFileTimeout": "60000",

    "ExpandReferenceComments": "false",
    "Compile": {
        "Mode": "External",
        "Extensions": [ ".ts" ],
        "ExtensionsWithNoOutput": [ ".d.ts" ],
        "OutDirectory": "../Eos.OperationalTool.UI/"
    },
    "References": [
        { "Path": "./scripts/angular.js" },
        { "Path": "./scripts/angular-route.js" },
        { "Path": "./scripts/angular-mocks.js" },
        { "Path": "./scripts/moment.js" },
        { "Includes": [ "*/tests/*/*.ts", "*/Client/*.js" ], "Excludes": [ "*.d.ts" ] }
    ],
    "Tests": [
        { "Includes": [ "*/tests/*/*.ts" ], "Excludes": [ "*.d.ts", "*/scripts/*/*.js" ] }
    ],
    "CodeCoverageExcludes": [ "*angular*.js", "*lodash*.js", "*moment*.js", "*tests*.ts", "*/interfaces/*.ts", "*highstock.js", "*jquery-2.1.0.js" ],
    "EnableCodeCoverage": "true"
}
```

**There is one new issue though that I'm hoping you can help with. I get 5 tests for each test that I'm expecting. All 5 are exactly the same. Any clue?**

Also, is there a way to have Chutzpah find new tests after adjusting the Chutzpah.json file? The only way I could get it to discover the tests was to close Visual Studio and re-open it.

**Comment by guyjci** [comment]
As an FYI for future readers - it all boiled down to paths and includes - seems I was including an include file with reference paths - and it was reading that to create more tests - hence the multiples of the same test.
Here's my final working copy of the Chutzpah.json file. 
```
{
    "Framework": "jasmine",
    "TestFileTimeout": "60000",
    "ExpandReferenceComments": "false",
    "EnableTestFileBatching":  "true",
    "Compile": {
        "Mode": "External",
        "Extensions": [ ".ts" ],
        "ExtensionsWithNoOutput": [ ".d.ts" ],
        "OutDirectory": "../Eos.OperationalTool.UI/"
    },
    "References": [
        { "Path": "./scripts/angular.js" },
        { "Path": "./scripts/angular-route.js" },
        { "Path": "./scripts/angular-mocks.js" },
        { "Path": "./scripts/moment.js" },
        { "Path": "../Eos.OperationalTool.UI/Client/js/app/" },
        { "Includes": [ "*/tests/*/*.ts", "*/Client/*.ts" ], "Excludes": [ "*.d.js", "*/tests/*/models/*.js", "*/tests/*/testingincludes.js"  ] }
    ],
    "Tests": [
        {"Includes": [ "*/tests/*.ts" ],  "Excludes": [ "*.d.ts", "*/scripts/*/*.ts", "*/tests/*/models/*.ts", "*/tests/*/testingincludes.ts" ] }
    ],
    "CodeCoverageExcludes": [ "*angular*.js", "*lodash*.js", "*moment*.js", "*tests*.ts", "*/interfaces/*.ts", "*highstock.js", "*jquery-2.1.0.js" ],
    "EnableCodeCoverage": "true"
}
```

I would call this issue resolved!

**Comment by IEvangelist** [comment]
With the updated chutzpah.json above we are now seeing duplicate tests.  While they are the exact same test, they show up twice... any ideas why?  Some tests seem to indicate that they are actually even executed twice.

![image](https://cloud.githubusercontent.com/assets/7679720/10769755/b23b464e-7cb5-11e5-8dbb-11192b5d5c3c.png)

**Comment by mmanela** [comment]
@IEvangelist This usually means your references are pulling in your test files somehow. Can you share a repro of your issue? Or show your chutzpah.json file

**Comment by mmanela** [comment]
@IEvangelist ...ping...

**Comment by IEvangelist** [comment]
@mmanela, sorry for the delay. Here is the `chutzpah.json` 

```javascript
{
    "Framework": "jasmine",
    "TestFileTimeout": "60000",
    "ExpandReferenceComments": "false",
    "EnableTestFileBatching":  "true",
    "Compile": {
        "Mode": "External",
        "Extensions": [ ".ts" ],
        "ExtensionsWithNoOutput": [ ".d.ts" ],
        "OutDirectory": "../Eos.OperationalTool.UI/"
    },
    "References": [
        { "Path": "./scripts/jquery-2.1.0.js" },
        { "Path": "./scripts/angular.js" },
        { "Path": "./scripts/angular-route.js" },
        { "Path": "./scripts/angular-mocks.js" },
        { "Path": "./scripts/lodash.js" },
        { "Path": "./scripts/moment.js" },
        { "Path": "./scripts/highstock.js" },
        { "Path": "./tests/filters/MockEosApp.js" },
        { "Includes": [ "*/tests/*/*.ts", "*/Client/*.ts" ], "Excludes": [ "*.d.js", "*/tests/*/models/*.js", "*/tests/*/testingincludes.js"  ] }
    ],
    "Tests": [
        {"Includes": [ "*/tests/*.ts" ],  "Excludes": [ "*.d.ts", "*/scripts/*/*.ts", "*/tests/*/models/*.ts", "*/tests/*/testingincludes.ts" ] }
    ],
    "CodeCoverageExcludes": [ "*angular*.js", "*lodash*.js", "*moment*.js", "*tests*.ts", "*/interfaces/*.ts", "*highstock.js", "*jquery-2.1.0.js" ],
    "EnableCodeCoverage": "true"
}
```

**Comment by mmanela** [comment]
It looks like you are included your tests twice. Both in the __References__ section as well as the __Tests__ section. This could cause them to show up more than once.

**Comment by IEvangelist** [comment]
Nice, that seems to have done the trick -- thank you!
