### ISSUE TITLE
System.ArgumentException: Illegal characters in path.

### ISSUE THREAD

**Issue by phillsta** [mmanela/chutzpah#441]
Hi,

Quite recently when trying to run the console directly, or via vs 2015 extension or vstest.console as an adapter I'm getting the following error:

`
Error: Error: System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean c
heckForDuplicates, Boolean needFullPath)
   at Chutzpah.Wrappers.FileSystemWrapper.GetFullPath(String path) in c:\Dev\chutzpah\Chutzpah\Wrappers\FileSystemWrappe
r.cs:line 105
   at Chutzpah.FileProbe.FindPath(String path, Predicate`1 pathExists) in c:\Dev\chutzpah\Chutzpah\FileProbe.cs:line 230

   at Chutzpah.FileProbe.FindFilePath(String path) in c:\Dev\chutzpah\Chutzpah\FileProbe.cs:line 72
   at Chutzpah.ReferenceProcessor.ProcessFilePathAsReference(HashSet`1 discoveredPaths, IFrameworkDefinition definition,
 String relativeProcessingPath, ChutzpahTestSettingsFile chutzpahTestSettings, String referencePath, List`1 referencedFi
les, ReferencePathSettings pathSettings) in c:\Dev\chutzpah\Chutzpah\ReferenceProcessor.cs:line 287
   at Chutzpah.ReferenceProcessor.GetReferencedFiles(List`1 referencedFiles, IFrameworkDefinition definition, ChutzpahTe
stSettingsFile chutzpahTestSettings) in c:\Dev\chutzpah\Chutzpah\ReferenceProcessor.cs:line 91
   at Chutzpah.TestContextBuilder.BuildContext(IEnumerable`1 files, TestOptions options) in c:\Dev\chutzpah\Chutzpah\Tes
tContextBuilder.cs:line 159
   at Chutzpah.TestContextBuilder.TryBuildContext(IEnumerable`1 files, TestOptions options, TestContext& context) in c:\
Dev\chutzpah\Chutzpah\TestContextBuilder.cs:line 202
   at Chutzpah.TestRunner.<>c__DisplayClass12.<BuildTestContexts>b__f(List`1 testFiles) in c:\Dev\chutzpah\Chutzpah\Test
Runner.cs:line 414
While Running:C:\Agent\_work\agent1\a2b808cd\Test Project\TestProejct.WebUI.Tests\wwwroot\tests\master.spec.js
`

File Path: "C:\Agent\_work\agent1\a2b808cd\Test Project\TestProejct.WebUI.Tests\wwwroot\tests\master.spec.js"
I ensure the double quotes are there when calling the command 

If I move the spec file directly to C: for example it works, I've also confirmed its not the space in the folder name as without the space the name issue occurs.

I'm thinking it has to do with the length of the file path...
Can anyone see what is going wrong or can confirm replication of this issue?

**Comment by phillsta** [comment]
I've also tried running the console directly from the directory itself with no luck

C:...\tests>  C:\Windows\ServiceProfiles\NetworkService\.dnx\packages\Chutzpah\4.1.0\tools\chutzpah.console.exe master.spec.js

**Comment by mmanela** [comment]
Thanks for posting your issue. I have tried to replicate this given the information you provided but it worked fine for 

#### Steps I did
1) Created a test file at this path ```"C:\Agent_work\agent1\a2b808cd\Test Project\TestProejct.WebUI.Tests\wwwroot\tests\master.spec.js"```

2) Filled it with the following contents

```
test("hello", function() {
ok(true);
});
```


3) Executed it from the command line:
```
chutzpah.console.exe .\master.spec.js
```


And it ran fine.

Can you upload a full sample that repros this issue that I can try to run locally?

**Comment by phillsta** [comment]
Hi,

I managed to pinpoint this issue to be the chutzpah.json config file. I had an entry in the reference paths with ** to denote any children directories i.e. scripts/**/*.test.js. Got used to using this shortcut within gulp.

When i removed this line it resolved the issue.
