### ISSUE TITLE
Chutzpah unable to execute tests on Visual Studio Online

### ISSUE THREAD

**Issue by rguerreiro** [mmanela/chutzpah#452]
I've been trying to run some angular unit tests with the Chutzpah test adapter on visual studio online and I keep getting the same error: "Error: "before each" hook".

I'm able to run the test locally, without any errors, inside Visual Studio (Test Explorer), with the Chutzpah console and also using the vstest.console.exe(`"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" test\Manager.Web.Test\Client\services\lookupService.spec.js /logger:trx /TestAdapterPath:"C:\Users\MyUser\.dnx\packages\Chutzpah"`).

Here are the full logs for the tests:
```
2016-01-14T16:43:28.9149598Z Executing the powershell script: C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\agents\default\tasks\VSTest\1.0.24\VSTest.ps1
2016-01-14T16:43:29.4126877Z ##[debug]Calling Invoke-VSTest for all test assemblies
2016-01-14T16:43:29.4346868Z Working folder: C:\a\1
2016-01-14T16:43:29.4356865Z Executing C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe "C:\a\1\s\test\Manager.Web.Test\Client\services\lookupService.spec.js"  /logger:trx /TestAdapterPath:"C:\Users\buildguest\.dnx\packages\Chutzpah"
2016-01-14T16:43:29.7476868Z Microsoft (R) Test Execution Command Line Tool Version 14.0.24720.0
2016-01-14T16:43:29.7486873Z Copyright (c) Microsoft Corporation.  All rights reserved.
2016-01-14T16:43:30.0776865Z Starting test execution, please wait...
2016-01-14T16:43:35.8727100Z ##[error]Error: Error: "before each" hook
2016-01-14T16:43:35.8737106Z ##[error]		at file:///C:/a/1/s/test/Manager.Web.Test/bower_components/angular/angular.js:4459:53
2016-01-14T16:43:35.8747100Z ##[error]		at forEach (file:///C:/a/1/s/test/Manager.Web.Test/bower_components/angular/angular.js:340:24)
2016-01-14T16:43:35.8767099Z ##[error]		at loadModules (file:///C:/a/1/s/test/Manager.Web.Test/bower_components/angular/angular.js:4419:12)
2016-01-14T16:43:35.8787096Z ##[error]		at createInjector (file:///C:/a/1/s/test/Manager.Web.Test/bower_components/angular/angular.js:4344:22)
2016-01-14T16:43:35.8797094Z ##[error]		at workFn (file:///C:/a/1/s/test/Manager.Web.Test/bower_components/angular-mocks/angular-mocks.js:2428:60)
2016-01-14T16:43:35.8807096Z ##[error]		at inject (file:///C:/a/1/s/test/Manager.Web.Test/bower_components/angular-mocks/angular-mocks.js:2411:41)
2016-01-14T16:43:35.8827095Z ##[error]		at file:///C:/a/1/s/test/Manager.Web.Test/Client/services/lookupService.spec.js:29:15
2016-01-14T16:43:35.8847101Z ##[error]		at run (file:///C:/Users/buildguest/.dnx/packages/Chutzpah/4.1.0/tools/TestFiles/mocha/mocha.js:4150:36)
2016-01-14T16:43:35.8857105Z ##[error]		at next (file:///C:/Users/buildguest/.dnx/packages/Chutzpah/4.1.0/tools/TestFiles/mocha/mocha.js:4410:13)
2016-01-14T16:43:35.8857105Z ##[error]		at file:///C:/Users/buildguest/.dnx/packages/Chutzpah/4.1.0/tools/TestFiles/mocha/mocha.js:4417:11
2016-01-14T16:43:35.8867108Z ##[error]		at run (file:///C:/Users/buildguest/.dnx/packages/Chutzpah/4.1.0/tools/TestFiles/mocha/mocha.js:4152:7)
2016-01-14T16:43:35.8867108Z ##[error]		at next (file:///C:/Users/buildguest/.dnx/packages/Chutzpah/4.1.0/tools/TestFiles/mocha/mocha.js:4410:13)
2016-01-14T16:43:35.8867108Z ##[error]		at file:///C:/Users/buildguest/.dnx/packages/Chutzpah/4.1.0/tools/TestFiles/mocha/mocha.js:4417:11
2016-01-14T16:43:35.8877111Z ##[error]		at run (file:///C:/Users/buildguest/.dnx/packages/Chutzpah/4.1.0/tools/TestFiles/mocha/mocha.js:4152:7)
2016-01-14T16:43:35.8877111Z ##[error]		at next (file:///C:/Users/buildguest/.dnx/packages/Chutzpah/4.1.0/tools/TestFiles/mocha/mocha.js:4410:13)
2016-01-14T16:43:35.8887110Z ##[error]		at file:///C:/Users/buildguest/.dnx/packages/Chutzpah/4.1.0/tools/TestFiles/mocha/mocha.js:4417:11
2016-01-14T16:43:35.8887110Z ##[error]		at run (file:///C:/Users/buildguest/.dnx/packages/Chutzpah/4.1.0/tools/TestFiles/mocha/mocha.js:4152:7)
2016-01-14T16:43:35.8897109Z ##[error]		at next (file:///C:/Users/buildguest/.dnx/packages/Chutzpah/4.1.0/tools/TestFiles/mocha/mocha.js:4410:13)
2016-01-14T16:43:35.8897109Z ##[error]		at file:///C:/Users/buildguest/.dnx/packages/Chutzpah/4.1.0/tools/TestFiles/mocha/mocha.js:4422:9
2016-01-14T16:43:35.8907118Z ##[error]		at timeslice (file:///C:/Users/buildguest/.dnx/packages/Chutzpah/4.1.0/tools/TestFiles/mocha/mocha.js:5404:27)
2016-01-14T16:43:35.8907118Z ##[error]While Running:C:\a\1\s\test\Manager.Web.Test\Client\services\lookupService.spec.js
2016-01-14T16:43:35.8907118Z ##[error]
2016-01-14T16:43:35.8917112Z ##[error]
2016-01-14T16:43:35.9967104Z Warning: No test is available in C:\a\1\s\test\Manager.Web.Test\Client\services\lookupService.spec.js. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.
2016-01-14T16:43:36.3107111Z Information: Additionally, you can try specifying '/UseVsixExtensions' command if the test discoverer & executor is installed on the machine as vsix extensions and your installation supports vsix extensions. Example: vstest.console.exe myTests.dll /UseVsixExtensions:true
2016-01-14T16:43:36.7787101Z ##[error]VSTest Test Run failed with exit code: 1
2016-01-14T16:43:36.7867113Z ##[warning]No results found to publish.
```

And this is the test file that it's trying to run:
```
var assert = chai.assert,
    expect = chai.expect,
    should = chai.should();

describe('lookup service tests', function () {
    var $httpBackend, lookupService;

    beforeEach(function () {
        // removing the parts I don't need
        angular.module('blocks.confirm', []);
        angular.module('blocks.datatables', []);
        angular.module('app.layout', []);
        angular.module('app.dashboard', []);
        angular.module('app.customer', []);
        angular.module('app.client', []);
    });

    beforeEach(function () {
        module(function ($provide) {
            // mocks
            $provide.constant('toastr', { options: { } });
            $provide.constant('moment', { });
        });
    });

    beforeEach(module('app'));

    beforeEach(function () {
        inject(function (_$httpBackend_) {
            $httpBackend = _$httpBackend_;
            //$httpBackend.whenGET('/api/lookup/appointments').respond({ data: [{ Id: 1, Name: 'Test 1' }, { Id: 2, Name: 'Test 2' }] });
        });
    });

    beforeEach(function () {
        inject(function (_lookupService_) {
            lookupService = _lookupService_;
        });
    });

    afterEach(function () {
        $httpBackend.verifyNoOutstandingExpectation();
        $httpBackend.verifyNoOutstandingRequest();
    });

    describe('getAppointments method', function () {

        it('should exist', function () {
            expect(lookupService.getAppointments).to.exist;
        });

        it('should call api and return array', function () {
            // arranje
            $httpBackend.expectGET('/api/lookup/appointments').respond([{ Id: 1, Name: 'Test 1' }, { Id: 2, Name: 'Test 2' }]);

            // act
            var result = lookupService.getAppointments();

            // assert
            result.should.eventually.be.length(2);

            $httpBackend.flush();
        });

        it('should call api only once when menthod is called multiple times', function () {
            // arranje
            $httpBackend.whenGET('/api/lookup/appointments').respond([{ Id: 1, Name: 'Test 1' }, { Id: 2, Name: 'Test 2' }]);

            // act
            lookupService.getAppointments();
            lookupService.getAppointments();
            lookupService.getAppointments();
            lookupService.getAppointments();
            lookupService.getAppointments();

            // assert
            $httpBackend.flush(1);
        });
    });
});
```

Also the content for the chutzpah.json file:
```
{
  "Framework": "mocha",
  "TestHarnessLocationMode": "SettingsFileAdjacent",
  "RootReferencePathMode": "SettingsFileDirectory",
  "References": [
    {
      "Path": "bower_components/chai/chai.js",
      "IsTestFrameworkFile": true
    },
    {
      "Path": "bower_components/chai-as-promised/chai-as-promised.js",
      "IsTestFrameworkFile": true
    },
    {
      "Path": "bower_components/sinon/lib/sinon.js",
      "IsTestFrameworkFile": true
    },
    { "Path": "bower_components/jquery/dist/jquery.js" },
    { "Path": "bower_components/angular/angular.js" },
    { "Path": "bower_components/angular-mocks/angular-mocks.js" },
    { "Path": "bower_components/angular-bootstrap/ui-bootstrap-tpls.js" },
    { "Path": "bower_components/datatables/media/js/jquery.dataTables.js" },
    { "Path": "bower_components/datatables/media/js/dataTables.bootstrap.js" },
    { "Path": "bower_components/datatables-responsive/js/dataTables.responsive.js" },
    { "Path": "bower_components/datatables-select/js/dataTables.select.js" },
    { "Path": "bower_components/angular-animate/angular-animate.js" },
    { "Path": "bower_components/angular-resource/angular-resource.js" },
    { "Path": "bower_components/ui-router/release/angular-ui-router.js" },
    { "Path": "bower_components/angular-loading-bar/build/loading-bar.js" },
    { "Path": "bower_components/angular-auto-value/angular-auto-value.js" },
    { "Path": "bower_components/angular-datatables/dist/angular-datatables.js" },
    { "Path": "bower_components/angular-datatables/dist/plugins/bootstrap/angular-datatables.bootstrap.js" },
    { "Path": "bower_components/angular-datatables/dist/plugins/select/angular-datatables.select.js" },
    { "Path": "bower_components/toastr/toastr.js" },
    { "Path": "bower_components/moment/moment.js" },
    { "Path": "../../src/Manager.Web/wwwroot/app/app.module.js" },
    { "Path": "../../src/Manager.Web/wwwroot/app/blocks/router/router.module.js" },
    { "Path": "../../src/Manager.Web/wwwroot/app/blocks/router/routeHelper.js" },
    { "Path": "../../src/Manager.Web/wwwroot/app/blocks/confirm/confirm.module.js" },
    { "Path": "../../src/Manager.Web/wwwroot/app/blocks/confirm/confirmHelper.js" },
    { "Path": "../../src/Manager.Web/wwwroot/app/blocks/datatables/datatables.module.js" },
    { "Path": "../../src/Manager.Web/wwwroot/app/blocks/datatables/datatablesHelper.js" },
    { "Path": "../../src/Manager.Web/wwwroot/app/core/app.config.js" },
    { "Path": "../../src/Manager.Web/wwwroot/app/core/app.constants.js" },
    { "Path": "../../src/Manager.Web/wwwroot/app/core/app.directives.js" },
    {
      "Path": "../../src/Manager.Web/wwwroot/app/core/services",
      "Includes": [ "*.js" ]
    },
    { "Path": "../../src/Manager.Web/wwwroot/app/layout/layout.module.js" },
    { "Path": "../../src/Manager.Web/wwwroot/app/layout/layout.config.js" },
    { "Path": "../../src/Manager.Web/wwwroot/app/layout/layout.controller.js" },
    { "Path": "../../src/Manager.Web/wwwroot/app/dashboard/dashboard.module.js" },
    { "Path": "../../src/Manager.Web/wwwroot/app/dashboard/dashboard.config.js" },
    { "Path": "../../src/Manager.Web/wwwroot/app/customer/customer.module.js" },
    { "Path": "../../src/Manager.Web/wwwroot/app/customer/customer.config.js" },
    { "Path": "../../src/Manager.Web/wwwroot/app/customer/customer.controller.js" },
    { "Path": "../../src/Manager.Web/wwwroot/app/client/client.module.js" },
    { "Path": "../../src/Manager.Web/wwwroot/app/client/client.config.js" },
    { "Path": "../../src/Manager.Web/wwwroot/app/client/client.controller.js" }
  ],
  "Tests": [
    {
      "Path": "Client",
      "Includes": [ "*.spec.js" ]
    }
  ]
}
```

**Comment by mmanela** [comment]
Can you provide a full repro (either a zip or a git project) I can grab and run locally?

**Comment by rguerreiro** [comment]
As I mentioned, the problem isn't locally but only on visual studio online. But later on I'll provide something for you to test with.

**Comment by mmanela** [comment]
Sure, once I have the sample I can run on VSOnline (now called VSTS) as well

**Comment by rguerreiro** [comment]
Here you go: https://github.com/rguerreiro/chutzpah-vso-test
You can also find a "Build definition.docx" that includes all the print screens needed for you to reproduce my build.

**Comment by mmanela** [comment]
Awesome. I probably won't be able to get to this for a few days but will touch back with you when I do.

**Comment by rguerreiro** [comment]
Any luck trying to reproduce this issue?

**Comment by mmanela** [comment]
Have not had a chance to try yet. Will respond back when I do.

**Comment by mmanela** [comment]
@rguerreiro Lost track of this, are you still having the issue?

**Comment by rguerreiro** [comment]
Hi @mmanela. I too lost track :)
We can close it because even though it ran without any issue on my local env it was throwing that error on VSTS. I've refactored the test code and now it runs on VSTS without any issue. Not sure what was the issue though.

Thanks
