### ISSUE TITLE
Single test run fails on VS 2015 Up 1

### ISSUE THREAD

**Issue by PashaPash** [mmanela/chutzpah#474]
Running a single test from the Text Explorer fails on my VS with the following error message:

> The specified test case was not found in the current result context (mapping test id to test node)

I have no Productivity Power Tools 2015 for Visual Studio 2015 installed, so it does not looks like a duplicate of #460

Strange thing is that happens only when I trying to run a *single* test from TE by right click / Run Selected Test.  
Running all the tests (Run All), or just all the tests in a single file works OK.

Test file content:

    test("test1", function () {
        expect(0);
    });

    test("test2", function () {
        expect(0);
    });

It is fails only if there are at least two tests are declared in the same file.   
Running test1 turning in green (passed) in Test Explorer AND logs the error message in the output.  
Running test2 are not turning in greed (so it remains in "not run" group) in Test Explorer AND logs the error message in the output.  

Please let me know it I should attach any additional traces for this issue.

Full trace (test1, then test2):

	devenv.exe Information: 0 : Time:13:59:59.7320530; Thread:1; Message:Begin Initial test container search
	devenv.exe Information: 0 : Time:13:59:59.7380552; Thread:1; Message:Chutzpah.json file cache cleared
	devenv.exe Information: 0 : Time:13:59:59.7430549; Thread:1; Message:Begin enumerating loaded projects for test files
	devenv.exe Information: 0 : Time:13:59:59.7540539; Thread:1; Message:Begin selecting potential test files from project 'c:\Projects\WebApplication4\WebApplication4\WebApplication4.csproj'
	devenv.exe Information: 0 : Time:13:59:59.7650532; Thread:1; Message:End selecting potential test files from project 'c:\Projects\WebApplication4\WebApplication4\WebApplication4.csproj'
	devenv.exe Information: 0 : Time:13:59:59.7710536; Thread:1; Message:Begin selecting potential test files from project ''
	devenv.exe Information: 0 : Time:13:59:59.7770535; Thread:1; Message:End selecting potential test files from project ''
	devenv.exe Information: 0 : Time:13:59:59.7830534; Thread:1; Message:End enumerating loaded projects for test files
	devenv.exe Information: 0 : Time:13:59:59.7890536; Thread:1; Message:Begin UpdateTestContainersAndFileWatchers
	devenv.exe Information: 0 : Time:13:59:59.7940558; Thread:1; Message:Adding watch on c:\projects\webapplication4\webapplication4\tests.js
	devenv.exe Information: 0 : Time:13:59:59.8030536; Thread:1; Message:Determining if 'c:\projects\webapplication4\webapplication4\tests.js' might be a test file
	devenv.exe Information: 0 : Time:13:59:59.8160567; Thread:1; Message:Chutzpah.json file not found given starting directory c:\projects\webapplication4\webapplication4
	devenv.exe Information: 0 : Time:13:59:59.8390530; Thread:1; Message:Assuming 'c:\projects\webapplication4\webapplication4\tests.js' is a test file
	devenv.exe Information: 0 : Time:13:59:59.8440562; Thread:1; Message:Added test container for 'c:\projects\webapplication4\webapplication4\tests.js'
	devenv.exe Information: 0 : Time:13:59:59.8510538; Thread:1; Message:End UpdateTestContainersAndFileWatchers
	devenv.exe Information: 0 : Time:13:59:59.8560527; Thread:1; Message:End Initial test container search
	devenv.exe Information: 0 : Time:13:59:59.8610531; Thread:1; Message:End GetTestContainers
	Informational: ------ Discover test started ------
	PROGRAM Information: 0 : Time:14:00:02.6053318; Thread:39; Message:Chutzpah.json file not found given starting directory c:\projects\webapplication4\webapplication4
	Informational: ========== Discover test finished: 2 found (0:00:04.3581685) ==========
	devenv.exe Information: 0 : Time:14:00:14.3016280; Thread:1; Message:Begin GetTestContainers
	devenv.exe Information: 0 : Time:14:00:14.3066251; Thread:1; Message:End GetTestContainers
	devenv.exe Information: 0 : Time:14:00:14.3116270; Thread:1; Message:Test container comparision 2/16/2016 1:54:59 PM vs 2/16/2016 1:54:59 PM for c:\projects\webapplication4\webapplication4\tests.js
	Informational: ------ Run test started ------
	PROGRAM Information: 0 : Time:14:00:14.4316258; Thread:39; Message:Chutzpah.json file not found given starting directory c:\projects\webapplication4\webapplication4
	PROGRAM Information: 0 : Time:14:00:16.2156052; Thread:6; Message:Chutzpah.json file not found given starting directory c:\projects\webapplication4\webapplication4
	Error: Error: System.AggregateException: One or more errors occurred. ---> System.Runtime.InteropServices.COMException: The specified test case was not found in the current result context (mapping test id to test node).
	   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
	   at WEX.TestExecution.FrameworkHandle.RecordStart(TestCase testCase)
	   at Chutzpah.VS2012.TestAdapter.ExecutionCallback.TestStarted(TestCase test)
	   at Chutzpah.Callbacks.ParallelRunnerCallbackAdapter.TestStarted(TestCase testCase)
	   at Chutzpah.TestCaseStreamReader.ReadFromStream(StreamReader stream, TestContext testContext, TestOptions testOptions, IList`1 streamingTestFileContexts, IList`1 deferredEvents, ITestMethodRunnerCallback callback, Boolean debugEnabled)
	   at Chutzpah.TestCaseStreamReader.<>c__DisplayClass8.<Read>b__2()
	   at System.Threading.Tasks.Task`1.InnerInvoke()
	   at System.Threading.Tasks.Task.Execute()
	   --- End of inner exception stack trace ---
	   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
	   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
	   at System.Threading.Tasks.Task`1.get_Result()
	   at Chutzpah.TestCaseStreamReader.Read(ProcessStream processStream, TestOptions testOptions, TestContext testContext, ITestMethodRunnerCallback callback, Boolean debugEnabled)
	   at Chutzpah.TestRunner.<>c__DisplayClass26.<InvokeTestRunner>b__23(ProcessStream processStream)
	   at Chutzpah.ProcessHelper.RunExecutableAndProcessOutput[T](String exePath, String arguments, Func`2 streamProcessor)
	   at Chutzpah.TestRunner.InvokeTestRunner(String headlessBrowserPath, TestOptions options, TestContext testContext, TestExecutionMode testExecutionMode, ITestMethodRunnerCallback callback)
	   at Chutzpah.TestRunner.<>c__DisplayClass15.<ExecuteTestContexts>b__14(TestContext testContext)
	---> (Inner Exception #0) System.Runtime.InteropServices.COMException (0x80070490): The specified test case was not found in the current result context (mapping test id to test node).
	   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
	   at WEX.TestExecution.FrameworkHandle.RecordStart(TestCase testCase)
	   at Chutzpah.VS2012.TestAdapter.ExecutionCallback.TestStarted(TestCase test)
	   at Chutzpah.Callbacks.ParallelRunnerCallbackAdapter.TestStarted(TestCase testCase)
	   at Chutzpah.TestCaseStreamReader.ReadFromStream(StreamReader stream, TestContext testContext, TestOptions testOptions, IList`1 streamingTestFileContexts, IList`1 deferredEvents, ITestMethodRunnerCallback callback, Boolean debugEnabled)
	   at Chutzpah.TestCaseStreamReader.<>c__DisplayClass8.<Read>b__2()
	   at System.Threading.Tasks.Task`1.InnerInvoke()
	   at System.Threading.Tasks.Task.Execute()<---

	While Running:c:\projects\webapplication4\webapplication4\tests.js

	Informational: ========== Run test finished: 1 run (0:00:03.345612) ==========
	devenv.exe Information: 0 : Time:14:00:20.6725246; Thread:1; Message:Begin GetTestContainers
	devenv.exe Information: 0 : Time:14:00:20.6805646; Thread:1; Message:End GetTestContainers
	devenv.exe Information: 0 : Time:14:00:20.6885249; Thread:1; Message:Test container comparision 2/16/2016 1:54:59 PM vs 2/16/2016 1:54:59 PM for c:\projects\webapplication4\webapplication4\tests.js
	Informational: ------ Run test started ------
	PROGRAM Information: 0 : Time:14:00:21.0762046; Thread:55; Message:Chutzpah.json file not found given starting directory c:\projects\webapplication4\webapplication4
	PROGRAM Information: 0 : Time:14:00:23.0753617; Thread:6; Message:Chutzpah.json file not found given starting directory c:\projects\webapplication4\webapplication4
	Error: Error: System.AggregateException: One or more errors occurred. ---> System.Runtime.InteropServices.COMException: The specified test case was not found in the current result context (mapping test id to test node).
	   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
	   at WEX.TestExecution.FrameworkHandle.RecordStart(TestCase testCase)
	   at Chutzpah.VS2012.TestAdapter.ExecutionCallback.TestStarted(TestCase test)
	   at Chutzpah.Callbacks.ParallelRunnerCallbackAdapter.TestStarted(TestCase testCase)
	   at Chutzpah.TestCaseStreamReader.ReadFromStream(StreamReader stream, TestContext testContext, TestOptions testOptions, IList`1 streamingTestFileContexts, IList`1 deferredEvents, ITestMethodRunnerCallback callback, Boolean debugEnabled)
	   at Chutzpah.TestCaseStreamReader.<>c__DisplayClass8.<Read>b__2()
	   at System.Threading.Tasks.Task`1.InnerInvoke()
	   at System.Threading.Tasks.Task.Execute()
	   --- End of inner exception stack trace ---
	   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
	   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
	   at System.Threading.Tasks.Task`1.get_Result()
	   at Chutzpah.TestCaseStreamReader.Read(ProcessStream processStream, TestOptions testOptions, TestContext testContext, ITestMethodRunnerCallback callback, Boolean debugEnabled)
	   at Chutzpah.TestRunner.<>c__DisplayClass26.<InvokeTestRunner>b__23(ProcessStream processStream)
	   at Chutzpah.ProcessHelper.RunExecutableAndProcessOutput[T](String exePath, String arguments, Func`2 streamProcessor)
	   at Chutzpah.TestRunner.InvokeTestRunner(String headlessBrowserPath, TestOptions options, TestContext testContext, TestExecutionMode testExecutionMode, ITestMethodRunnerCallback callback)
	   at Chutzpah.TestRunner.<>c__DisplayClass15.<ExecuteTestContexts>b__14(TestContext testContext)
	---> (Inner Exception #0) System.Runtime.InteropServices.COMException (0x80070490): The specified test case was not found in the current result context (mapping test id to test node).
	   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
	   at WEX.TestExecution.FrameworkHandle.RecordStart(TestCase testCase)
	   at Chutzpah.VS2012.TestAdapter.ExecutionCallback.TestStarted(TestCase test)
	   at Chutzpah.Callbacks.ParallelRunnerCallbackAdapter.TestStarted(TestCase testCase)
	   at Chutzpah.TestCaseStreamReader.ReadFromStream(StreamReader stream, TestContext testContext, TestOptions testOptions, IList`1 streamingTestFileContexts, IList`1 deferredEvents, ITestMethodRunnerCallback callback, Boolean debugEnabled)
	   at Chutzpah.TestCaseStreamReader.<>c__DisplayClass8.<Read>b__2()
	   at System.Threading.Tasks.Task`1.InnerInvoke()
	   at System.Threading.Tasks.Task.Execute()<---

	While Running:c:\projects\webapplication4\webapplication4\tests.js

	Informational: ========== Run test finished: 0 run (0:00:03.7735092) ==========

**Comment by mmanela** [comment]
I have not seen this before. I will test more soon and see. 

Do you have resharper installed?

**Comment by DaBeSoft** [comment]
I have the same Problem, and i do have resharper installed

**Comment by mmanela** [comment]
And this is what update 1 installed too? Does it repro if you disable resharper?

**Comment by PashaPash** [comment]
@mmanela no resharper installed. It is a clean VS 2015 SP1 with standard set of addons like Azure and Nuget.

**Comment by DaBeSoft** [comment]
@mmanela Disabled resharper, still happens.

Other than resharper and the standard set of addons (Enterprise FULL Installation, so there are many installed addons like tons of Pythontools, loads of azure Tools, and some Xamarin/Crossplattform/Mobile Tools), i do have DevExpress and NUint3 installed.

Here is my trace, just in case:

```
Error: System.AggregateException: One or more errors occurred. ---> System.Runtime.InteropServices.COMException: The specified test case was not found in the current result context (mapping test id to test node).
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at WEX.TestExecution.FrameworkHandle.RecordStart(TestCase testCase)
   at Chutzpah.VS2012.TestAdapter.ExecutionCallback.TestStarted(TestCase test)
   at Chutzpah.Callbacks.ParallelRunnerCallbackAdapter.TestStarted(TestCase testCase)
   at Chutzpah.TestCaseStreamReader.ReadFromStream(StreamReader stream, TestContext testContext, TestOptions testOptions, IList`1 streamingTestFileContexts, IList`1 deferredEvents, ITestMethodRunnerCallback callback, Boolean debugEnabled)
   at Chutzpah.TestCaseStreamReader.<>c__DisplayClass8.<Read>b__2()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Chutzpah.TestCaseStreamReader.Read(ProcessStream processStream, TestOptions testOptions, TestContext testContext, ITestMethodRunnerCallback callback, Boolean debugEnabled)
   at Chutzpah.TestRunner.<>c__DisplayClass26.<InvokeTestRunner>b__23(ProcessStream processStream)
   at Chutzpah.ProcessHelper.RunExecutableAndProcessOutput[T](String exePath, String arguments, Func`2 streamProcessor)
   at Chutzpah.TestRunner.InvokeTestRunner(String headlessBrowserPath, TestOptions options, TestContext testContext, TestExecutionMode testExecutionMode, ITestMethodRunnerCallback callback)
   at Chutzpah.TestRunner.<>c__DisplayClass15.<ExecuteTestContexts>b__14(TestContext testContext)
---> (Inner Exception #0) System.Runtime.InteropServices.COMException (0x80070490): The specified test case was not found in the current result context (mapping test id to test node).
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at WEX.TestExecution.FrameworkHandle.RecordStart(TestCase testCase)
   at Chutzpah.VS2012.TestAdapter.ExecutionCallback.TestStarted(TestCase test)
   at Chutzpah.Callbacks.ParallelRunnerCallbackAdapter.TestStarted(TestCase testCase)
   at Chutzpah.TestCaseStreamReader.ReadFromStream(StreamReader stream, TestContext testContext, TestOptions testOptions, IList`1 streamingTestFileContexts, IList`1 deferredEvents, ITestMethodRunnerCallback callback, Boolean debugEnabled)
   at Chutzpah.TestCaseStreamReader.<>c__DisplayClass8.<Read>b__2()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---
```

**Comment by Namstel** [comment]
I too am receiving this error when running a single test. Running them all works just fine.

This is what my test code looks like:

```
/// <reference path="simple.js" />
/// <reference path="default.js" />
/*jshint undef:false*/

describe("Double number function", function () {
    it("should double the number given. 2 should become 4.", function () {
        expect(doubleNumber(2)).toBe(4);
    });
});

describe("doWork", function () {
    it("should do 5+4+3+2+1 and return 15 when parameter is 5.", function () {
        expect(doWork(5)).toBe(15);
    });
    it("should do something else when parameter is < 1.", function () {
        expect(doWork(-1)).toBe();
    });
});
```

And here's the output:

```
------ Run test started ------
Error: System.AggregateException: One or more errors occurred. ---> System.Runtime.InteropServices.COMException: The specified test case was not found in the current result context (mapping test id to test node).
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at WEX.TestExecution.FrameworkHandle.RecordStart(TestCase testCase)
   at Chutzpah.VS2012.TestAdapter.ExecutionCallback.TestStarted(TestCase test)
   at Chutzpah.Callbacks.ParallelRunnerCallbackAdapter.TestStarted(TestCase testCase)
   at Chutzpah.TestCaseStreamReader.ReadFromStream(StreamReader stream, TestContext testContext, TestOptions testOptions, IList`1 streamingTestFileContexts, IList`1 deferredEvents, ITestMethodRunnerCallback callback, Boolean debugEnabled)
   at Chutzpah.TestCaseStreamReader.<>c__DisplayClass8.<Read>b__2()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Chutzpah.TestCaseStreamReader.Read(ProcessStream processStream, TestOptions testOptions, TestContext testContext, ITestMethodRunnerCallback callback, Boolean debugEnabled)
   at Chutzpah.TestRunner.<>c__DisplayClass26.<InvokeTestRunner>b__23(ProcessStream processStream)
   at Chutzpah.ProcessHelper.RunExecutableAndProcessOutput[T](String exePath, String arguments, Func`2 streamProcessor)
   at Chutzpah.TestRunner.InvokeTestRunner(String headlessBrowserPath, TestOptions options, TestContext testContext, TestExecutionMode testExecutionMode, ITestMethodRunnerCallback callback)
   at Chutzpah.TestRunner.<>c__DisplayClass15.<ExecuteTestContexts>b__14(TestContext testContext)
---> (Inner Exception #0) System.Runtime.InteropServices.COMException (0x80070490): The specified test case was not found in the current result context (mapping test id to test node).
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at WEX.TestExecution.FrameworkHandle.RecordStart(TestCase testCase)
   at Chutzpah.VS2012.TestAdapter.ExecutionCallback.TestStarted(TestCase test)
   at Chutzpah.Callbacks.ParallelRunnerCallbackAdapter.TestStarted(TestCase testCase)
   at Chutzpah.TestCaseStreamReader.ReadFromStream(StreamReader stream, TestContext testContext, TestOptions testOptions, IList`1 streamingTestFileContexts, IList`1 deferredEvents, ITestMethodRunnerCallback callback, Boolean debugEnabled)
   at Chutzpah.TestCaseStreamReader.<>c__DisplayClass8.<Read>b__2()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

While Running:c:\users\niels.van.amstel\documents\visual studio 2015\projects\jsunittesting\jsunittesting\lib\test.js

========== Run test finished: 0 run (0:00:07,4937646) ==========
```

**Comment by mmanela** [comment]
Thanks for the stack traces and errors. I am unable to repro locally yet but I am investigating this further.

**Comment by mmanela** [comment]
Thanks everyone. I am able to repro and I understand the issue. The VS test adapter framework changed in the most recent version and no longer is a fan for how Chutzpah reports its test results when running an individual test. I am in talks with the team who owns the framework to evaluate if the right fix is on their side or Chutzpah's side. I will respond back with progress.

Sorry for the inconvenience.

**Comment by mmanela** [comment]
Update: The VS test adapter has found the issue and fixed it. It should be included in VS 2015 Update 2!

**Comment by mmanela** [comment]
Thanks everyone for reporting and helping find the issue.
