### ISSUE TITLE
VS2015U2 and Jasmine 1.3.1 - Tests run in browser just bring up empty browser window

### ISSUE THREAD

**Issue by jmwolfe** [mmanela/chutzpah#501]
Environment:
Visual Studio 2015 Update 2.
Jasmine 1.3.1 included as a nuget package at the package level. 
Chutzpah menu extension for VS version 4.2.1
Test Explorer Chutzpah plugin is not installed

Issue:
When running a test suite in the browser (IE11 and latest chrome), jasmine simply doesn't execute. And the problem seems to be this bit of code in the test.html:

```
`              // If we are not running in chutzpah then run the tests onload
             if (!window.chutzpah) {
                  var currentWindowOnload = window.onload;

                  window.onload = function() {
                        if (currentWindowOnload) {
                            currentWindowOnload();
                        }

                        jasmineEnv.execute();
                    };
                }`

```

Apparently, when run from VS2015, the generated test.html is  including the chutzpah_boot.js file which is defining window.chutzpah so jasmineEnv.execute never runs in the code bit above (at the end of test.html file).

If we set a debug point in Chrome and change window.chutzpah to false or undefine it, then all the tests run correctly when we click Continue.

At this point, we have to hack the template to adjust this logic so we can run tests in the browser.

Any suggestions as to what's wrong here?

**Comment by windump** [comment]
Change this:
chutzpah/Chutzpah/TestFiles/Jasmine/v1/jasmine.html
```
           else {
                // If we are not running in chutzpah then run the tests onload
                if (!window.chutzpah) {
```
To this:
```
            else {
                // If we are not running in chutzpah then run the tests onload
                if (!window.chutzpah.usingModuleLoader) {
```

**Comment by jmwolfe** [comment]
Thanks, WD. Technically, if you have installed the menu extension, you need to edit:

C:\Users\<yourUserId>\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\zqj4240j.wb4\TestFiles\Jasmine\v1\jasmine.html

As expected, upgrading to Jasmine 2.2 doesn't fix the issue.

So unless anyone can explain why this is only happening to me, this seems like a pretty big defect. Is every user of this version using this workaround?

**Comment by mmanela** [comment]
I will look into this and fix it soon once I an confirm it.

**Comment by jmwolfe** [comment]
Thanks, Matthew. 

Correction to my previous assertion: this issue WAS resolved by using Jasmine 2, as the logic in v2/jasmine.html is different. Probably why not many people have hit this.  We had to upgrade Chutzpah as we were upgrading to Visual Studio 2015.

**Comment by jmwolfe** [comment]
Also, when I use the above workaround, it seems to cause jasmine to throw an error when running in PhantomJS:

`	Error: Injector already created, can not register a module! in file:///d:/svn/cmgr/trunk/contentmanager/ContentManager/Scripts/angular-mocks.js (line 2020)
		at execute (file:///C:/Users/tqgyso0/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/n5mkuxqm.atr/TestFiles/jasmine/v1/jasmine.js:1064:22)
		at next_ (file:///C:/Users/tqgyso0/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/n5mkuxqm.atr/TestFiles/jasmine/v1/jasmine.js:2096:38)
		at start (file:///C:/Users/tqgyso0/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/n5mkuxqm.atr/TestFiles/jasmine/v1/jasmine.js:2049:13)
		at execute (file:///C:/Users/tqgyso0/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/n5mkuxqm.atr/TestFiles/jasmine/v1/jasmine.js:2376:19)
		at next_ (file:///C:/Users/tqgyso0/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/n5mkuxqm.atr/TestFiles/jasmine/v1/jasmine.js:2096:38)
		at start (file:///C:/Users/tqgyso0/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/n5mkuxqm.atr/TestFiles/jasmine/v1/jasmine.js:2049:13)
		at execute (file:///C:/Users/tqgyso0/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/n5mkuxqm.atr/TestFiles/jasmine/v1/jasmine.js:2521:19)
		at next_ (file:///C:/Users/tqgyso0/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/n5mkuxqm.atr/TestFiles/jasmine/v1/jasmine.js:2096:38)
		at start (file:///C:/Users/tqgyso0/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/n5mkuxqm.atr/TestFiles/jasmine/v1/jasmine.js:2049:13)
		at execute (file:///C:/Users/tqgyso0/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/n5mkuxqm.atr/TestFiles/jasmine/v1/jasmine.js:2521:19)
		at next_ (file:///C:/Users/tqgyso0/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/n5mkuxqm.atr/TestFiles/jasmine/v1/jasmine.js:2096:38)
		at start (file:///C:/Users/tqgyso0/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/n5mkuxqm.atr/TestFiles/jasmine/v1/jasmine.js:2049:13)
		at execute (file:///C:/Users/tqgyso0/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/n5mkuxqm.atr/TestFiles/jasmine/v1/jasmine.js:2143:19)
		at execute (file:///C:/Users/tqgyso0/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/n5mkuxqm.atr/TestFiles/jasmine/v1/jasmine.js:802:30)
		at onload (file:///d:/svn/cmgr/trunk/contentmanager/unittests/jasmine/_Chutzpah.aeb9a38408eb281d7d77197cd28552cc.test.html:83:43)
	TypeError: null is not an object (evaluating 'currentSpec.$injector') in file:///d:/svn/cmgr/trunk/contentmanager/ContentManager/Scripts/angular-mocks.js (line 1963)
		at execute (file:///C:/Users/tqgyso0/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/n5mkuxqm.atr/TestFiles/jasmine/v1/jasmine.js:1064:22)
		at next_ (file:///C:/Users/tqgyso0/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/n5mkuxqm.atr/TestFiles/jasmine/v1/jasmine.js:2096:38)
		at start (file:///C:/Users/tqgyso0/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/n5mkuxqm.atr/TestFiles/jasmine/v1/jasmine.js:2049:13)
		at execute (file:///C:/Users/tqgyso0/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/n5mkuxqm.atr/TestFiles/jasmine/v1/jasmine.js:2376:19)
		at next_ (file:///C:/Users/tqgyso0/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/n5mkuxqm.atr/TestFiles/jasmine/v1/jasmine.js:2096:38)
		at start (file:///C:/Users/tqgyso0/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/n5mkuxqm.atr/TestFiles/jasmine/v1/jasmine.js:2049:13)
		at execute (file:///C:/Users/tqgyso0/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/n5mkuxqm.atr/TestFiles/jasmine/v1/jasmine.js:2521:19)
		at next_ (file:///C:/Users/tqgyso0/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/n5mkuxqm.atr/TestFiles/jasmine/v1/jasmine.js:2096:38)
		at start (file:///C:/Users/tqgyso0/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/n5mkuxqm.atr/TestFiles/jasmine/v1/jasmine.js:2049:13)
		at execute (file:///C:/Users/tqgyso0/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/n5mkuxqm.atr/TestFiles/jasmine/v1/jasmine.js:2521:19)
		at next_ (file:///C:/Users/tqgyso0/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/n5mkuxqm.atr/TestFiles/jasmine/v1/jasmine.js:2096:38)
		at start (file:///C:/Users/tqgyso0/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/n5mkuxqm.atr/TestFiles/jasmine/v1/jasmine.js:2049:13)
		at execute (file:///C:/Users/tqgyso0/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/n5mkuxqm.atr/TestFiles/jasmine/v1/jasmine.js:2143:19)
		at execute (file:///C:/Users/tqgyso0/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/n5mkuxqm.atr/TestFiles/jasmine/v1/jasmine.js:802:30)
		at onload (file:///d:/svn/cmgr/trunk/contentmanager/unittests/jasmine/_Chutzpah.aeb9a38408eb281d7d77197cd28552cc.test.html:83:43)
in d:\svn\cmgr\trunk\contentmanager\unittests\jasmine\exportcategoryctrltests.js (line 119)
`

**Comment by drewfreyling** [comment]
I hit this issue as well. I got around it by using a custom test harness with the following:
```
 if (window.chutzpah) {
                    
                    var currentWindowOnload = window.onload;
                    //in chutzpah window.onload is set to run the tests already for us but if we run in browser it is not. We don't need this on jasmine 2.
                    window.onload = function() {
                        if (currentWindowOnload) {
                            currentWindowOnload();
                        } else {
                            jasmineEnv.execute();
                        }
                    };
                }
```

**Comment by mmanela** [comment]
Will push a point release soon with this

**Comment by jmwolfe** [comment]
Thanks, @drewfreyling , @mmanela. I'll be looking for it.

**Comment by mmanela** [comment]
Chutzpah 4.2.2 is released and it contains the fix

**Comment by jmwolfe** [comment]
I have installed 4.2.2, and now I'm seeing this:

`I have installed 4.2.2, and now I'm seeing this:

`------ Test started: File: D:\SVN\cmgr\trunk\ContentManager\UnitTests\Jasmine\ExportCategoryModalWindowDirectiveTests.js ------
61 passed, 0 failed, 61 total (chutzpah).

Error: ReferenceError: Can't find variable: jasmine
at startJasmine in undefined (line 11)
at onload  (line 36)
at exit  (line 0)
at writeEvent in phantomjs://code/chutzpahRunner.js (line 78)
at captureLogMessage in phantomjs://code/chutzpahRunner.js (line 91)
at log  (line 0)
at log  (line 6)
at reportRunnerResults  (line 52)
in file:///C:/Users/jwolfe/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/wzhatb5u.xi0/TestFiles/jasmine/v1/jasmine.js (line 1788)
at finishCallback in file:///C:/Users/jwolfe/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/wzhatb5u.xi0/TestFiles/jasmine/v1/jasmine.js (line 2160)
in file:///C:/Users/jwolfe/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/wzhatb5u.xi0/TestFiles/jasmine/v1/jasmine.js (line 2144)
at next_ in file:///C:/Users/jwolfe/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/wzhatb5u.xi0/TestFiles/jasmine/v1/jasmine.js (line 2106)
at onComplete in file:///C:/Users/jwolfe/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/wzhatb5u.xi0/TestFiles/jasmine/v1/jasmine.js (line 2092)
at finish in file:///C:/Users/jwolfe/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/wzhatb5u.xi0/TestFiles/jasmine/v1/jasmine.js (line 2478)
in file:///C:/Users/jwolfe/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/wzhatb5u.xi0/TestFiles/jasmine/v1/jasmine.js (line 2522)
at next_ in file:///C:/Users/jwolfe/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/wzhatb5u.xi0/TestFiles/jasmine/v1/jasmine.js (line 2106)
at onComplete in file:///C:/Users/jwolfe/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/wzhatb5u.xi0/TestFiles/jasmine/v1/jasmine.js (line 2092)
at finish in file:///C:/Users/jwolfe/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/wzhatb5u.xi0/TestFiles/jasmine/v1/jasmine.js (line 2478)
in file:///C:/Users/jwolfe/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/wzhatb5u.xi0/TestFiles/jasmine/v1/jasmine.js (line 2522)
at next_ in file:///C:/Users/jwolfe/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/wzhatb5u.xi0/TestFiles/jasmine/v1/jasmine.js (line 2106)
at onComplete in file:///C:/Users/jwolfe/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/wzhatb5u.xi0/TestFiles/jasmine/v1/jasmine.js (line 2092)
at finish in file:///C:/Users/jwolfe/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/wzhatb5u.xi0/TestFiles/jasmine/v1/jasmine.js (line 2350)
in file:///C:/Users/jwolfe/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/wzhatb5u.xi0/TestFiles/jasmine/v1/jasmine.js (line 2377)
at next_ in file:///C:/Users/jwolfe/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/wzhatb5u.xi0/TestFiles/jasmine/v1/jasmine.js (line 2106)
in file:///C:/Users/jwolfe/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/wzhatb5u.xi0/TestFiles/jasmine/v1/jasmine.js (line 2086)
While Running:D:\path\to\tests\testsuite.js
Error: ReferenceError: Can't find variable: jasmine
at startJasmine in undefined (line 11)
at onload  (line 36)
at exit  (line 0)
at writeEvent in phantomjs://code/chutzpahRunner.js (line 78)
at captureLogMessage in phantomjs://code/chutzpahRunner.js (line 91)
at log  (line 0)
at log  (line 6)
at reportRunnerResults  (line 52)
in file:///C:/Users/jwolfe/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/wzhatb5u.xi0/TestFiles/jasmine/v1/jasmine.js (line 1788)
at finishCallback in file:///C:/Users/jwolfe/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/wzhatb5u.xi0/TestFiles/jasmine/v1/jasmine.js (line 2160)
in file:///C:/Users/jwolfe/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/wzhatb5u.xi0/TestFiles/jasmine/v1/jasmine.js (line 2144)
at next_ in file:///C:/Users/jwolfe/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/wzhatb5u.xi0/TestFiles/jasmine/v1/jasmine.js (line 2106)
at onComplete in file:///C:/Users/jwolfe/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/wzhatb5u.xi0/TestFiles/jasmine/v1/jasmine.js (line 2092)
at finish in file:///C:/Users/jwolfe/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/wzhatb5u.xi0/TestFiles/jasmine/v1/jasmine.js (line 2478)
in file:///C:/Users/jwolfe/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/wzhatb5u.xi0/TestFiles/jasmine/v1/jasmine.js (line 2522)
at next_ in file:///C:/Users/jwolfe/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/wzhatb5u.xi0/TestFiles/jasmine/v1/jasmine.js (line 2106)
at onComplete in file:///C:/Users/jwolfe/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/wzhatb5u.xi0/TestFiles/jasmine/v1/jasmine.js (line 2092)
at finish in file:///C:/Users/jwolfe/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/wzhatb5u.xi0/TestFiles/jasmine/v1/jasmine.js (line 2478)
in file:///C:/Users/jwolfe/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/wzhatb5u.xi0/TestFiles/jasmine/v1/jasmine.js (line 2522)
at next_ in file:///C:/Users/jwolfe/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/wzhatb5u.xi0/TestFiles/jasmine/v1/jasmine.js (line 2106)
at onComplete in file:///C:/Users/jwolfe/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/wzhatb5u.xi0/TestFiles/jasmine/v1/jasmine.js (line 2092)
at finish in file:///C:/Users/jwolfe/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/wzhatb5u.xi0/TestFiles/jasmine/v1/jasmine.js (line 2350)
in file:///C:/Users/jwolfe/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/wzhatb5u.xi0/TestFiles/jasmine/v1/jasmine.js (line 2377)
at next_ in file:///C:/Users/jwolfe/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/wzhatb5u.xi0/TestFiles/jasmine/v1/jasmine.js (line 2106)
in file:///C:/Users/jwolfe/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/wzhatb5u.xi0/TestFiles/jasmine/v1/jasmine.js (line 2086)
While Running:D:\path\to\tests\testsuite.js
========== Total Tests: 61 passed, 0 failed, 61 total ==========
``

`

**Comment by mmanela** [comment]
Thanks for reporting the error. I have a fix but I am not 100% sure why it happens. 

As for the open in browser issue, do you root cause why it is failing?

**Comment by jmwolfe** [comment]
Yes. I looked into it. It was an error in the test. IE was doing something the test didn't expect. No problem with Chutzpah or Jasmine.

**Comment by drewfreyling** [comment]
I'm getting the can't find jasmine variable as well under 4.2.2. Came up after I loaded VS 2015, edited a html file and clicked build.

**Comment by mmanela** [comment]
Can you repro this consistently? If so, Can you share the steps?

**Comment by drewfreyling** [comment]
@mmanela I haven't been able to repro it consistently.
