### ISSUE TITLE
Test not working on cmd line but works with openInBrowser

### ISSUE THREAD

**Issue by drewfreyling** [mmanela/chutzpah#509]
I'm currently getting a strange issue where angular will throw an error about not being able to discover my factory but it works if you use `/openInBrowser`. I'm not sure if this is a limitation of phantomjs here or a chutzpah issue. What makes it even more bizarre if you move `innerFunc` outside the if statement to reduce nesting it works.

```
   Test 'pricing service:Should discover my service' failed
        Error: [$injector:unpr] Unknown provider: pricingServiceProvider <- pricingService
http://errors.angularjs.org/1.5.3/$injector/unpr?p0=pricingServiceProvider%20%3C-%20pricingService (line 4418)
                at getService (file:///C:/dev/globalx.web/GlobalX.Web/Scripts/angular.js:4571:46)
                at file:///C:/dev/globalx.web/GlobalX.Web/Scripts/angular.js:4423:48
                at getService (file:///C:/dev/globalx.web/GlobalX.Web/Scripts/angular.js:4571:46)
                at injectionArgs (file:///C:/dev/globalx.web/GlobalX.Web/Scripts/angular.js:4595:68)
                at invoke (file:///C:/dev/globalx.web/GlobalX.Web/Scripts/angular.js:4617:31)
        TypeError: undefined is not a constructor (evaluating 'expect(pricingService).toNotBe(null)') in file:///C:/dev/globalx.web/GlobalX.Web/jstests/unit/products/viccerts/common/services/pricingServiceSpec.js (line 15)
                at attemptSync (file:///C:/Chutzpah.4.2.1/TestFiles/jasmine/v2/jasmine.js:1886:28)
                at run (file:///C:/Chutzpah.4.2.1/TestFiles/jasmine/v2/jasmine.js:1874:20)
                at execute (file:///C:/Chutzpah.4.2.1/TestFiles/jasmine/v2/jasmine.js:1859:13)
                at queueRunnerFactory (file:///C:/Chutzpah.4.2.1/TestFiles/jasmine/v2/jasmine.js:697:42)
                at execute (file:///C:/Chutzpah.4.2.1/TestFiles/jasmine/v2/jasmine.js:359:28)
in C:\dev\globalx.web\GlobalX.Web\jstests\unit\products\viccerts\common\services\pricingServiceSpec.js (line 14)
```

```
(function (angular) {
    "use strict";

    angular
        .module("test")
        .factory("pricingService", PricingService);

    function PricingService() {
        return {};

        function getTotalPrice() {
            if (1 == 1) {

                function innerFunc() {

                }
            }
        }
    }
}(angular));
```

```
(function() {
    "use strict";
    describe("pricing service", function() {
        var pricingService;

        beforeEach(function() {
            module("test");

            inject(function(_pricingService_) {
                pricingService = _pricingService_;
            });
        });

        it("Should discover my service", function() {
            expect(pricingService).toNotBe(null);
        });
    });
}());
```

**Comment by drewfreyling** [comment]
I've left out the module definition and my chutzpah.json for brevity. Issue appears with either Jasmine 1 or 2 and I'm using angular 1.5.3.

**Comment by mmanela** [comment]
Can you provide a repro I can run locally?

**Comment by mmanela** [comment]
Closing since no repro was given. Please re-open if still valid
