### ISSUE TITLE
TFS Build: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by SeanSobey** [mmanela/chutzpah#511]
Hi,

I am using Chutzpah on my dev machine as well as during our TFS nightly builds. The builds were running fine, with code coverage as well, but at some point started showing the issue mentioned in [#340](https://github.com/mmanela/chutzpah/issues/340) and [#493](https://github.com/mmanela/chutzpah/issues/493).

I upgraded the Chutzpah files for the build server reference assemblies, as reccomended in one of those issues, to the latest version (4.2.1), and I think I also made some changes to the projects chutzpah.json files too.

TFS build now no longer runs js tests, and for each js file gives the following exception in TFS build log:
<code>
Error: System.NullReferenceException: Object reference not set to an instance of an object.
    at Chutzpah.TestHarness.BuildTags(IEnumerable`1 referencedFilePaths)
    at Chutzpah.TestHarness..ctor(ChutzpahTestSettingsFile chutzpahTestSettings, TestOptions testOptions, IEnumerable "1 referencedFiles, IFileSystemWrapper fileSystem)
    at Chutzpah.TestHarnessBuilder.CreateTestHarness(TestContext testContext, TestOptions options)
    at Chutzpah.TestRunner.c__DisplayClass15.b__14(TestContext testContext)
</code>

Providing a repo to replicate this may be difficult, since the tests run fine in VS 2015 and only appear on TFS tests. But I can run builds anytime manually and provide any of our config/code files to help resolve this issue.

**Comment by SeanSobey** [comment]
I found the problem I think, there recently was a file added to Chutzpah (TestFiles/chutzpah_boot.js), and this needed to be added to the BuildAssemblies folder. Once I added and checked into TFS everything worked perfectly.
