### ISSUE TITLE
Cannot Debug Unit Tests

### ISSUE THREAD

**Issue by MichaelSienknecht** [mmanela/chutzpah#566]
Hi,
I know there was already an Issue to that topic but I couldn’t find a solution in it. I am using VS2015 Enterprise update 3. I have the same problem as DaBeSoft in #476. I can debug the code but not the Tests. I get the same error:
Error: System.Runtime.InteropServices.COMException (0x8971001E): Ausnahme von HRESULT: 0x8971001E
   bei EnvDTE80.Process2.Attach2(Object Engines)
   bei Chutzpah.VS.Common.DteHelpers.DebugAttachToProcess(Int32 subjectProcessId, String debugEngine)
   bei Chutzpah.VS.Common.VsDebuggerTestLauncher.LaunchTest(TestContext testContext)
   bei Chutzpah.TestRunner.<>c__DisplayClass15.<ExecuteTestContexts>b__14(TestContext testContext)

Reinstalled my system fresh but did not help. Would be grateful for some feedback.

**Comment by turquoiseowl** [comment]
@MichaelSienknecht Do you mean you are able to debug Javascript scripts in IE from Visual Studio? That's a good starting point to get that working as there are quite a few settings in IE that can prevent debugging. (I've just searched my notes and can't find reference to them. Maybe they got documented with Chutzpah?)

If that is working, I can't add anything more than when last time this came up.

**Comment by MichaelSienknecht** [comment]
@turquoiseowl Yes that is what i mean. I can debug javascript in IE but when i try to debug the javascript Tests, IE opens blank and nothing happens.

**Comment by turquoiseowl** [comment]
That should mean it is not IE settings causing the problem.

If you're inclined to, perhaps you could try with your own build of Chutzpah and debug the DebugAttachToProcess method. One possibility is it's an OS issue (I've only tested witn Windows 7) and upgrading from EnvDTE80 to a later version would help. Another might be a security issue (I typically test using an acocunt with UAC turned off and as an Admin account).

**Comment by BartlomiejBarc** [comment]
Hi,

I debug Jasmine tests being run with Chutzpah in Visual Studio Professional 2015 Update 3. However, debugging is processed successfully only when I start it with right click in .js test file and chose option "Run Chutzpah With > Debugger" from the context menu.

When I trigger debugging by right click on tests and "Debug Selected Tests" option or right click in .js file and select "Debug Tests" option, the following exception is thrown:

> Exception thrown: 'System.ObjectDisposedException' in mscorlib.dll
System.Transactions Critical: 0 : <TraceRecord xmlns="http://schemas.microsoft.com/2004/10/E2ETraceEvent/TraceRecord" Severity="Critical"><TraceIdentifier>http://msdn.microsoft.com/TraceCodes/System/ActivityTracing/2004/07/Reliability/Exception/Unhandled</TraceIdentifier><Description>Unhandled exception</Description><AppDomain>vstest.executionengine.x86.exe</AppDomain><Exception><ExceptionType>System.ObjectDisposedException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType><Message>Safe handle has been closed</Message><StackTrace>   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean&amp;amp; success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean&amp;amp; success)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.NativeMethods.uv_async_send(UvAsyncHandle handle)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.async_send(UvAsyncHandle handle)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.PostCloseHandle(Action`1 callback, IntPtr handle)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvHandle.ReleaseHandle()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvStreamHandle.ReleaseHandle()
   at System.Runtime.InteropServices.SafeHandle.InternalFinalize()
   at System.Runtime.InteropServices.SafeHandle.Dispose(Boolean disposing)
   at System.Runtime.InteropServices.SafeHandle.Finalize()</StackTrace><ExceptionString>System.ObjectDisposedException: Safe handle has been closed
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean&amp;amp; success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean&amp;amp; success)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.NativeMethods.uv_async_send(UvAsyncHandle handle)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.async_send(UvAsyncHandle handle)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.PostCloseHandle(Action`1 callback, IntPtr handle)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvHandle.ReleaseHandle()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvStreamHandle.ReleaseHandle()
   at System.Runtime.InteropServices.SafeHandle.InternalFinalize()
   at System.Runtime.InteropServices.SafeHandle.Dispose(Boolean disposing)
   at System.Runtime.InteropServices.SafeHandle.Finalize()</ExceptionString></Exception></TraceRecord>
The program '[6880] vstest.executionengine.x86.exe' has exited with code 0 (0x0).
'iexplore.exe' (Script): Loaded 'Script Code (Windows Internet Explorer)'.

Why is that happening?

**Comment by mmanela** [comment]
That is new, I will take a look at that. But you confirmed it does work from the other menu item?

**Comment by BartlomiejBarc** [comment]
Yes, the option "Run Chutzpah With > Debugger" works fine.

**Comment by mmanela** [comment]
Cool, Ill test and investigate when I get some time.

**Comment by johnnyjob** [comment]
I'm getting the same exception in VS 2013 Premium Update 5, on Windows Server 2012 Standard.
Run VS NOT as an admin, UAC is ON.
Debugging via context menu extension ("Run Chutzpah With > Debugger") works just fine.

**Comment by andre719mv** [comment]
I have this error with enabled server mode
"Server": {
    "Enabled": true,
    "RootPath": "./"
  }
