### ISSUE TITLE
crash running code coverage in browser

### ISSUE THREAD

**Issue by gregveres** [mmanela/chutzpah#593]
HI @mmanela 

this just started happening on this one file. When I go to look at the code coverage Chutzpah crashes before it can load up the browser. I haven't been able to see if i can get you a small sample to show the crash but here is the stack output:

```
------ Test started: File: c:\users\gregv\source\repos\squashspider\squashspider\squashspider\scripts\tests\app\boxleague\boxleaguemanageviewmodeltests.ts ------
Error: System.AggregateException: One or more errors occurred. ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Chutzpah.Coverage.SourceMapDotNetLineCoverageMapper.GetOriginalFileLineExecutionCounts(Nullable`1[] generatedSourceLineExecutionCounts, Int32 sourceLineCount, ReferencedFile referencedFile)
   at Chutzpah.Coverage.BlanketJsCoverageEngine.DeserializeCoverageObject(String json, TestContext testContext)
   at Chutzpah.TestCaseStreamReader.FireCoverageObject(ITestMethodRunnerCallback callback, StreamingTestFileContext testFileContext, JsRunnerOutput jsRunnerOutput)
   at Chutzpah.TestCaseStreamReader.ReadFromStream(StreamReader stream, TestContext testContext, TestOptions testOptions, IList`1 streamingTestFileContexts, IList`1 deferredEvents, ITestMethodRunnerCallback callback, Boolean debugEnabled)
   at Chutzpah.TestCaseStreamReader.<>c__DisplayClass5_0.<Read>b__2()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Chutzpah.TestCaseStreamReader.Read(ProcessStream processStream, TestOptions testOptions, TestContext testContext, ITestMethodRunnerCallback callback, Boolean debugEnabled)
   at Chutzpah.TestRunner.<>c__DisplayClass42_0.<InvokeTestRunner>b__0(ProcessStream processStream)
   at Chutzpah.ProcessHelper.RunExecutableAndProcessOutput[T](String exePath, String arguments, Func`2 streamProcessor)
   at Chutzpah.TestRunner.InvokeTestRunner(String headlessBrowserPath, TestOptions options, TestContext testContext, TestExecutionMode testExecutionMode, ITestMethodRunnerCallback callback)
   at Chutzpah.TestRunner.<>c__DisplayClass39_0.<ExecuteTestContexts>b__0(TestContext testContext)
---> (Inner Exception #0) System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Chutzpah.Coverage.SourceMapDotNetLineCoverageMapper.GetOriginalFileLineExecutionCounts(Nullable`1[] generatedSourceLineExecutionCounts, Int32 sourceLineCount, ReferencedFile referencedFile)
   at Chutzpah.Coverage.BlanketJsCoverageEngine.DeserializeCoverageObject(String json, TestContext testContext)
   at Chutzpah.TestCaseStreamReader.FireCoverageObject(ITestMethodRunnerCallback callback, StreamingTestFileContext testFileContext, JsRunnerOutput jsRunnerOutput)
   at Chutzpah.TestCaseStreamReader.ReadFromStream(StreamReader stream, TestContext testContext, TestOptions testOptions, IList`1 streamingTestFileContexts, IList`1 deferredEvents, ITestMethodRunnerCallback callback, Boolean debugEnabled)
   at Chutzpah.TestCaseStreamReader.<>c__DisplayClass5_0.<Read>b__2()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

While Running:c:\users\gregv\source\repos\squashspider\squashspider\squashspider\scripts\tests\app\boxleague\boxleaguemanageviewmodeltests.ts
========== Total Tests: 0 passed, 0 failed, 0 total ==========

```

**Comment by gregveres** [comment]
I should mention that I am using typescript and I am running 4.3.3.

Looking at the code I suspect the problem is that match.lineNumber is greater than sourceLineCount. But I don't know the code so ... 

```
          var accumulated = new List<int?>(new int?[sourceLineCount + 1]);
            for (var i = 1; i < generatedSourceLineExecutionCounts.Length; i++)
            {
                int? generatedCount = generatedSourceLineExecutionCounts[i];
                if (generatedCount == null)
                {
                    continue;
                }

                var matches = consumer.OriginalPositionsFor(i);
                if (matches.Any())
                {
                    foreach (var match in matches)
                    {
                        if (!IsCurrentFile(match.File, referencedFile)) { continue; }

                        accumulated[match.LineNumber] = (accumulated[match.LineNumber] ?? 0) + generatedCount.Value;
                    }
                }
            }

```

**Comment by mmanela** [comment]
A repro would be really helpful here to see what case it is not handling.

**Comment by gregveres** [comment]
yea the repo is difficult. I tried for a bit, but when I removed certain test cases, it would stop happening. When I put them back in and removed other test cases it would stop happening. so I couldn't really narrow it down to anything less than the entire file. 

Is it possible to give me a hint as to what "might" be causing it and I could look at my code to see if there is something in there that is similar to the "might"?

**Comment by mmanela** [comment]
@Pablissimo You have any idea on this?

**Comment by Pablissimo** [comment]
Hard to diagnose without the source map and the original .ts file, but if it's proving troublesome to repro I might be able to conceive a way to force the issue by a bit of reverse engineering... I've got a spare hour just now, lemme look.

**Comment by Pablissimo** [comment]
From a quick scan, looks like @gregveres's assessment of where the problem might be is probably correct - if the source map claimed that a JS line mapped to a non-existent TS line then you'd get the behaviour you're seeing. Not sure how that would happen, if the map file was out of sync with the TS file maybe.

I can propose a patch that would make it fail safe, though in this instance I'm not sure what I'd do - just ignore the line mapping issue (at which point how much can you trust any of the other mappings)? Alternatively I could check the TS line number is in range and if not then throw an exception with enough diagnostic info to help pin down what file's the issue.

@gregveres - are you doing anything exciting like compiling your TS all into the same output file?

**Comment by gregveres** [comment]
No all the files are staying as individual files. Let me check if the map file is read only for some reason and therefore old and not getting updated.

**Comment by gregveres** [comment]
Nope all the map files are new. They have all been generated today or are in areas I am not working in. But this has given me something to look at. I will look at all the files that get pulled in to test this one ts file and I will see if any of the map files have references that are outside the range.

give me a few minutes....

**Comment by gregveres** [comment]
Ok that wasn't very fruitful.

Since the source maps are Base64 and compressed, I don't know how to read them. I did open all the files in the browser debugger when debugging the jasmine run. All of the TS files look like they were mapping properly to the JS file (based on looking at the highlighting on the line numbers, all the dark line numbers that represent JS code matched the TS code). There weren't any that seemed to go on beyond the TS file.

I also cleaned the project and rebuilt it to ensure that the map files were fresh. it still crashes. If I knew the file name of where it was crashing that might help.

**Comment by Pablissimo** [comment]
How many source maps are we talking about that relate to the test that fails? I can if you attach them/can email them probably get a basic 'they claim the corresponding TS file has this many lines' metric, it's possible there's a bug in SourceMapDotNet such that it's mishandling something and claiming more lines exist than actually do...

You're also able to sort-of do that yourself, SourceMapDotNet's on my GitHub page but there's no console app or anything (but it'd be straightforward to cobble something together with it to read your maps and see how it handles them).

**Comment by gregveres** [comment]
There are 24 map files. If you email me at greg . veres at rogers . com, I will reply with the map files.

**Comment by Pablissimo** [comment]
FYI @mmanela - @gregveres has emailed me his source maps, we're chatting offline but we'll report back if we get anywhere!
