### ISSUE TITLE
"UseSourceMaps": true using vstest.console.exe generate FileNotFoundException Newtonsoft.Json

### ISSUE THREAD

**Issue by Steffe1971** [mmanela/chutzpah#666]
Trying to use the UseSourceMaps setting in chutzpah.json when running a code coverage with chutzpah and vstest.console.exe. If i set the UseSourceMaps to false everything is working as expected.

Seems that there is some old reference to Newtonsoft.Json in the SourceMapDotNet dll. The Newtonsoft.Json used in Chtuzpah seeams to be 9.0.1

Using Chtuzpah 4.3.5

`Error: Error: System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
   at SourceMapDotNet.SourceMapConsumer..ctor(String sourceMapJson)
   at Chutzpah.Coverage.SourceMapDotNetLineCoverageMapper.GetConsumer(String mapFileContents)
   at Chutzpah.Coverage.SourceMapDotNetLineCoverageMapper.GetOriginalFileLineExecutionCounts(Nullable`1[] generatedSourceLineExecutionCounts, Int32 sourceLineCount, ReferencedFile referencedFile)
   at Chutzpah.Coverage.BlanketJsCoverageEngine.DeserializeCoverageObject(String json, TestContext testContext)
   at Chutzpah.TestCaseStreamReader.FireCoverageObject(ITestMethodRunnerCallback callback, StreamingTestFileContext testFileContext, JsRunnerOutput jsRunnerOutput)
   at Chutzpah.TestCaseStreamReader.ReadFromStream(StreamReader stream, TestContext testContext, TestOptions testOptions, IList`1 streamingTestFileContexts, IList`1 deferredEvents, ITestMethodRunnerCallback callback, Boolean debugEnabled)

   at Chutzpah.TestCaseStreamReader.<>c__DisplayClass5_0.<Read>b__2()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Chutzpah.TestCaseStreamReader.Read(ProcessStream processStream, TestOptions testOptions, TestContext testContext, ITestMethodRunnerCallback callback, Boolean debugEnabled)
   at Chutzpah.TestRunner.<>c__DisplayClass42_0.<InvokeTestRunner>b__0(ProcessStream processStream)
   at Chutzpah.ProcessHelper.RunExecutableAndProcessOutput[T](String exePath, String arguments, Func`2 streamProcessor)
   at Chutzpah.TestRunner.InvokeTestRunner(String headlessBrowserPath, TestOptions options, TestContext testContext, TestExecutionMode testExecutionMode, ITestMethodRunnerCallback callback)
   at Chutzpah.TestRunner.<>c__DisplayClass39_0.<ExecuteTestContexts>b__0(TestContext testContext)`

**Comment by mmanela** [comment]
@Pablissimo Any idea?

**Comment by Steffe1971** [comment]
Workaround for this issue is to register the Newtonsoft.Json assembly that SourceMapDotNet used in the .NET GAC then everything works as it should.
