### ISSUE TITLE
VS2015 Chutzpah not running

### ISSUE THREAD

**Issue by mwpowellhtx** [mmanela/chutzpah#683]
Hello,

I am trying for Mocha+Chai to run with Chutzpah, but so far running into errors:

```
> cmd.exe /c gulp -b "G:\Source\Kingdom Software\JavaScript\ExtensionsJS\Testing\src\ExtensionsJS.Array" --color --gulpfile "G:\Source\Kingdom Software\JavaScript\ExtensionsJS\Testing\src\ExtensionsJS.Array\Gulpfile.js" test
[18:22:32] Using gulpfile G:\Source\Kingdom Software\JavaScript\ExtensionsJS\Testing\src\ExtensionsJS.Array\Gulpfile.js
[18:22:32] Starting 'test'...
module.js:540
    throw err;
    ^
Error: Cannot find module 'should'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (G:\Source\Kingdom Software\JavaScript\ExtensionsJS\Testing\src\ExtensionsJS.Array\Tests\Scripts\ExtensionsJS\arr-tests.js:8:14)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at G:\Source\Kingdom Software\JavaScript\ExtensionsJS\Testing\src\ExtensionsJS.Array\node_modules\mocha\lib\mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (G:\Source\Kingdom Software\JavaScript\ExtensionsJS\Testing\src\ExtensionsJS.Array\node_modules\mocha\lib\mocha.js:228:14)
    at Mocha.run (G:\Source\Kingdom Software\JavaScript\ExtensionsJS\Testing\src\ExtensionsJS.Array\node_modules\mocha\lib\mocha.js:536:10)
    at Object.<anonymous> (G:\Source\Kingdom Software\JavaScript\ExtensionsJS\Testing\src\ExtensionsJS.Array\node_modules\mocha\bin\_mocha:582:18)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
{ Error: Command failed: mocha G:\Source\Kingdom Software\JavaScript\ExtensionsJS\Testing\src\ExtensionsJS.Array\Tests\Scripts\ExtensionsJS\arr-tests.js --colors --clear-require-cache --ignore-leaks --exit
module.js:540
    throw err;
    ^
Error: Cannot find module 'should'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (G:\Source\Kingdom Software\JavaScript\ExtensionsJS\Testing\src\ExtensionsJS.Array\Tests\Scripts\ExtensionsJS\arr-tests.js:8:14)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at G:\Source\Kingdom Software\JavaScript\ExtensionsJS\Testing\src\ExtensionsJS.Array\node_modules\mocha\lib\mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (G:\Source\Kingdom Software\JavaScript\ExtensionsJS\Testing\src\ExtensionsJS.Array\node_modules\mocha\lib\mocha.js:228:14)
    at Mocha.run (G:\Source\Kingdom Software\JavaScript\ExtensionsJS\Testing\src\ExtensionsJS.Array\node_modules\mocha\lib\mocha.js:536:10)
    at Object.<anonymous> (G:\Source\Kingdom Software\JavaScript\ExtensionsJS\Testing\src\ExtensionsJS.Array\node_modules\mocha\bin\_mocha:582:18)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
    at Promise.all.then.arr (G:\Source\Kingdom Software\JavaScript\ExtensionsJS\Testing\src\ExtensionsJS.Array\node_modules\execa\index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 1,
  killed: false,
  stdout: '',
  stderr: 'module.js:540\r\n    throw err;\r\n    ^\r\n\r\nError: Cannot find module \'should\'\r\n    at Function.Module._resolveFilename (module.js:538:15)\r\n    at Function.Module._load (module.js:468:25)\r\n    at Module.require (module.js:587:17)\r\n    at require (internal/module.js:11:18)\r\n    at Object.<anonymous> (G:\\Source\\Kingdom Software\\JavaScript\\ExtensionsJS\\Testing\\src\\ExtensionsJS.Array\\Tests\\Scripts\\ExtensionsJS\\arr-tests.js:8:14)\r\n    at Module._compile (module.js:643:30)\r\n    at Object.Module._extensions..js (module.js:654:10)\r\n    at Module.load (module.js:556:32)\r\n    at tryModuleLoad (module.js:499:12)\r\n    at Function.Module._load (module.js:491:3)\r\n    at Module.require (module.js:587:17)\r\n    at require (internal/module.js:11:18)\r\n    at G:\\Source\\Kingdom Software\\JavaScript\\ExtensionsJS\\Testing\\src\\ExtensionsJS.Array\\node_modules\\mocha\\lib\\mocha.js:231:27\r\n    at Array.forEach (<anonymous>)\r\n    at Mocha.loadFiles (G:\\Source\\Kingdom Software\\JavaScript\\ExtensionsJS\\Testing\\src\\ExtensionsJS.Array\\node_modules\\mocha\\lib\\mocha.js:228:14)\r\n    at Mocha.run (G:\\Source\\Kingdom Software\\JavaScript\\ExtensionsJS\\Testing\\src\\ExtensionsJS.Array\\node_modules\\mocha\\lib\\mocha.js:536:10)\r\n    at Object.<anonymous> (G:\\Source\\Kingdom Software\\JavaScript\\ExtensionsJS\\Testing\\src\\ExtensionsJS.Array\\node_modules\\mocha\\bin\\_mocha:582:18)\r\n    at Module._compile (module.js:643:30)\r\n    at Object.Module._extensions..js (module.js:654:10)\r\n    at Module.load (module.js:556:32)\r\n    at tryModuleLoad (module.js:499:12)\r\n    at Function.Module._load (module.js:491:3)\r\n    at Function.Module.runMain (module.js:684:10)\r\n    at startup (bootstrap_node.js:187:16)\r\n    at bootstrap_node.js:608:3\r\n',
  failed: true,
  signal: null,
  cmd: 'mocha G:\\Source\\Kingdom Software\\JavaScript\\ExtensionsJS\\Testing\\src\\ExtensionsJS.Array\\Tests\\Scripts\\ExtensionsJS\\arr-tests.js --colors --clear-require-cache --ignore-leaks --exit',
  timedOut: false,
  message: 'Command failed: mocha G:\\Source\\Kingdom Software\\JavaScript\\ExtensionsJS\\Testing\\src\\ExtensionsJS.Array\\Tests\\Scripts\\ExtensionsJS\\arr-tests.js --colors --clear-require-cache --ignore-leaks --exit\nmodule.js:540\r\n    throw err;\r\n    ^\r\n\r\nError: Cannot find module \'should\'\r\n    at Function.Module._resolveFilename (module.js:538:15)\r\n    at Function.Module._load (module.js:468:25)\r\n    at Module.require (module.js:587:17)\r\n    at require (internal/module.js:11:18)\r\n    at Object.<anonymous> (G:\\Source\\Kingdom Software\\JavaScript\\ExtensionsJS\\Testing\\src\\ExtensionsJS.Array\\Tests\\Scripts\\ExtensionsJS\\arr-tests.js:8:14)\r\n    at Module._compile (module.js:643:30)\r\n    at Object.Module._extensions..js (module.js:654:10)\r\n    at Module.load (module.js:556:32)\r\n    at tryModuleLoad (module.js:499:12)\r\n    at Function.Module._load (module.js:491:3)\r\n    at Module.require (module.js:587:17)\r\n    at require (internal/module.js:11:18)\r\n    at G:\\Source\\Kingdom Software\\JavaScript\\ExtensionsJS\\Testing\\src\\ExtensionsJS.Array\\node_modules\\mocha\\lib\\mocha.js:231:27\r\n    at Array.forEach (<anonymous>)\r\n    at Mocha.loadFiles (G:\\Source\\Kingdom Software\\JavaScript\\ExtensionsJS\\Testing\\src\\ExtensionsJS.Array\\node_modules\\mocha\\lib\\mocha.js:228:14)\r\n    at Mocha.run (G:\\Source\\Kingdom Software\\JavaScript\\ExtensionsJS\\Testing\\src\\ExtensionsJS.Array\\node_modules\\mocha\\lib\\mocha.js:536:10)\r\n    at Object.<anonymous> (G:\\Source\\Kingdom Software\\JavaScript\\ExtensionsJS\\Testing\\src\\ExtensionsJS.Array\\node_modules\\mocha\\bin\\_mocha:582:18)\r\n    at Module._compile (module.js:643:30)\r\n    at Object.Module._extensions..js (module.js:654:10)\r\n    at Module.load (module.js:556:32)\r\n    at tryModuleLoad (module.js:499:12)\r\n    at Function.Module._load (module.js:491:3)\r\n    at Function.Module.runMain (module.js:684:10)\r\n    at startup (bootstrap_node.js:187:16)\r\n    at bootstrap_node.js:608:3\r\n\n',
  name: 'Error',
  stack: 'Error: Command failed: mocha G:\\Source\\Kingdom Software\\JavaScript\\ExtensionsJS\\Testing\\src\\ExtensionsJS.Array\\Tests\\Scripts\\ExtensionsJS\\arr-tests.js --colors --clear-require-cache --ignore-leaks --exit\nmodule.js:540\r\n    throw err;\r\n    ^\r\n\r\nError: Cannot find module \'should\'\r\n    at Function.Module._resolveFilename (module.js:538:15)\r\n    at Function.Module._load (module.js:468:25)\r\n    at Module.require (module.js:587:17)\r\n    at require (internal/module.js:11:18)\r\n    at Object.<anonymous> (G:\\Source\\Kingdom Software\\JavaScript\\ExtensionsJS\\Testing\\src\\ExtensionsJS.Array\\Tests\\Scripts\\ExtensionsJS\\arr-tests.js:8:14)\r\n    at Module._compile (module.js:643:30)\r\n    at Object.Module._extensions..js (module.js:654:10)\r\n    at Module.load (module.js:556:32)\r\n    at tryModuleLoad (module.js:499:12)\r\n    at Function.Module._load (module.js:491:3)\r\n    at Module.require (module.js:587:17)\r\n    at require (internal/module.js:11:18)\r\n    at G:\\Source\\Kingdom Software\\JavaScript\\ExtensionsJS\\Testing\\src\\ExtensionsJS.Array\\node_modules\\mocha\\lib\\mocha.js:231:27\r\n    at Array.forEach (<anonymous>)\r\n    at Mocha.loadFiles (G:\\Source\\Kingdom Software\\JavaScript\\ExtensionsJS\\Testing\\src\\ExtensionsJS.Array\\node_modules\\mocha\\lib\\mocha.js:228:14)\r\n    at Mocha.run (G:\\Source\\Kingdom Software\\JavaScript\\ExtensionsJS\\Testing\\src\\ExtensionsJS.Array\\node_modules\\mocha\\lib\\mocha.js:536:10)\r\n    at Object.<anonymous> (G:\\Source\\Kingdom Software\\JavaScript\\ExtensionsJS\\Testing\\src\\ExtensionsJS.Array\\node_modules\\mocha\\bin\\_mocha:582:18)\r\n    at Module._compile (module.js:643:30)\r\n    at Object.Module._extensions..js (module.js:654:10)\r\n    at Module.load (module.js:556:32)\r\n    at tryModuleLoad (module.js:499:12)\r\n    at Function.Module._load (module.js:491:3)\r\n    at Function.Module.runMain (module.js:684:10)\r\n    at startup (bootstrap_node.js:187:16)\r\n    at bootstrap_node.js:608:3\r\n\n\n    at Promise.all.then.arr (G:\\Source\\Kingdom Software\\JavaScript\\ExtensionsJS\\Testing\\src\\ExtensionsJS.Array\\node_modules\\execa\\index.js:236:11)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)',
  plugin: 'gulp-mocha',
  showProperties: true,
  showStack: false }
[18:22:33] 'test' errored after 654 ms
[18:22:33] Error in plugin "gulp-mocha"
Message:
    Command failed: mocha G:\Source\Kingdom Software\JavaScript\ExtensionsJS\Testing\src\ExtensionsJS.Array\Tests\Scripts\ExtensionsJS\arr-tests.js --colors --clear-require-cache --ignore-leaks --exit
module.js:540
    throw err;
    ^
Error: Cannot find module 'should'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (G:\Source\Kingdom Software\JavaScript\ExtensionsJS\Testing\src\ExtensionsJS.Array\Tests\Scripts\ExtensionsJS\arr-tests.js:8:14)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at G:\Source\Kingdom Software\JavaScript\ExtensionsJS\Testing\src\ExtensionsJS.Array\node_modules\mocha\lib\mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (G:\Source\Kingdom Software\JavaScript\ExtensionsJS\Testing\src\ExtensionsJS.Array\node_modules\mocha\lib\mocha.js:228:14)
    at Mocha.run (G:\Source\Kingdom Software\JavaScript\ExtensionsJS\Testing\src\ExtensionsJS.Array\node_modules\mocha\lib\mocha.js:536:10)
    at Object.<anonymous> (G:\Source\Kingdom Software\JavaScript\ExtensionsJS\Testing\src\ExtensionsJS.Array\node_modules\mocha\bin\_mocha:582:18)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
Details:
    code: 1
    killed: false
    stdout: 
    stderr: module.js:540
    throw err;
    ^
Error: Cannot find module 'should'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (G:\Source\Kingdom Software\JavaScript\ExtensionsJS\Testing\src\ExtensionsJS.Array\Tests\Scripts\ExtensionsJS\arr-tests.js:8:14)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at G:\Source\Kingdom Software\JavaScript\ExtensionsJS\Testing\src\ExtensionsJS.Array\node_modules\mocha\lib\mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (G:\Source\Kingdom Software\JavaScript\ExtensionsJS\Testing\src\ExtensionsJS.Array\node_modules\mocha\lib\mocha.js:228:14)
    at Mocha.run (G:\Source\Kingdom Software\JavaScript\ExtensionsJS\Testing\src\ExtensionsJS.Array\node_modules\mocha\lib\mocha.js:536:10)
    at Object.<anonymous> (G:\Source\Kingdom Software\JavaScript\ExtensionsJS\Testing\src\ExtensionsJS.Array\node_modules\mocha\bin\_mocha:582:18)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
    failed: true
    signal: null
    cmd: mocha G:\Source\Kingdom Software\JavaScript\ExtensionsJS\Testing\src\ExtensionsJS.Array\Tests\Scripts\ExtensionsJS\arr-tests.js --colors --clear-require-cache --ignore-leaks --exit
    timedOut: false
Process terminated with code 1.
```

My test file looks like:

```JavaScript
var mocha = require("mocha");
var should = require("should");

describe("Some basic testing",
    function () {
        describe("is defined",
            function () {
                (0).should.equal(0);
                (0).should.equal(0);
                [0, 1, 2].should.be.instanceof(Array).and.have.length(3);
            }
        );
    }
);
```

And I've got a ``Chutzpah.json`` that looks like:

```JavaScript
{
    "Framework": "mocha",
    "MochaInterface": "bdd",
    "References": [
        { "Path": "../node_modules/chai/chai.js" }
    ]
}
```

Which all I want to also facilitate via ``gulp``:

```JavaScript
gulp.task("test",
    function() {
        return gulp.src(cfg.tests + "/*.js", { read: false })
            .pipe(mocha({
                clearRequireCache: true,
                ignoreLeaks: true,
                exit: true
            }))
            .on("error", console.error);
    }
);
```

I expect to see results reported to the test runner, but what I am receiving is a ``Jasmine`` browser window with *"No spec found"*, which leads me to believe that somehow ``Jasmine`` is my test runner in spite of having installed ``Chutzpah``? Never mind, connecting Mocha+Chai+Should-isms to the tests.

Thoughts?

**Comment by mwpowellhtx** [comment]
I have it mostly running, but for Gulp Chutzpah integration.

Where are the chutzpah.whatever.exe runners located? Whether console, runner, etc?

Thank you!

**Comment by mwpowellhtx** [comment]
Ubiquity, or lack there of, appears to be a thing. Please forgive the density of my thinking, but thus far there appears to be at least two paradigms that would preclude me from a full integration with my *VS2015* experience.

First, if I do the following in my unit test file:

```JavaScript
/// <reference path="../../../node_modules/mocha/mocha.js"/>
/// <reference path="../../../node_modules/chai/chai.js"/>

var expect = chai.expect;
var assert = chai.assert;

describe(..., it(...));
describe(..., it(...));
describe(..., it(...));
```

Then I get comprehension via the *Visual Studio Test Runner*.

However, then *Gulp'ing* utilizing ``mocha`` breaks:

```JavaScript
gulp.task("test",
    function() {
        return gulp.src(cfg.spec + "/*.js")
            .pipe(mocha());
    }
);
```

If I try to ``.pipe(chutzpah())``, this wants the runner executable path, which escapes me at the moment. I do not know where it is, in spite of finding the *VS Extensions* folder.

However, if I want ``Gulp``/build-time-event support, then I must specify the test module as follows:

```JavaScript
var expect = require("chai").expect;
var assert = require("chai").assert;

describe(..., it(...));
describe(..., it(...));
describe(..., it(...));
```

Which supports *Gulp'ing* via ``mocha``. But which breaks compatibility with the *Test Runner*.

I think the missing piece to glue it all together is knowing the path of the ``Chutzpah`` runner. Otherwise, I'm kind of stuck with one flavor or the other.

Perhaps I could configure either mode one way or the other, but that just seems like an unnecessarily ugly approach to me.

Thoughts?

**Comment by mmanela** [comment]
1. You can get Chutzpah exe from the github releases page or from nuget or chocolatey. https://github.com/mmanela/chutzpah/releases/tag/v4.3.6

2. Are you using an AMD module loader? If so, you can configure chutzpah to work with that . However, for VS intellisense you may still need the /// reference comments (but I am not sure)

**Comment by mwpowellhtx** [comment]
Thanks, I got it mostly sorted out I think.
