### ISSUE TITLE
Unable to run tests due to non-FIPS-compliant algorithm

### ISSUE THREAD

**Issue by JimmyTheChimp** [mmanela/chutzpah#690]
I get the following error when I try to run my tests using the contest menu extension:

Error: System.InvalidOperationException: This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.
   at System.Security.Cryptography.SHA1Managed..ctor()
   at Chutzpah.Utility.Hasher.<>c.<.ctor>b__2_0()
   at System.Threading.ThreadLocal`1.GetValueSlow()
   at System.Threading.ThreadLocal`1.get_Value()
   at Chutzpah.Utility.Hasher.Hash(String input)
   at Chutzpah.TestHarnessBuilder.CreateTestHarness(TestContext testContext, TestOptions options)
   at Chutzpah.TestRunner.<>c__DisplayClass39_0.<ExecuteTestContexts>b__0(TestContext testContext)
While Running:C:\Users\594106\Source\Repos\PPI_ThePricingApp_R3\PricingApp\PricingApp\Scripts\app\Workspace.spec.js

**Comment by mmanela** [comment]
Yea, Chutzpah uses Sha1 for hashing right now which FIPS does not like.

**Comment by mat1234** [comment]
Any status on this?  This is still an issue that prevents us from using Chutzpah.

**Comment by mmanela** [comment]
I am not working on this change but if someone would like to contribute a PR to fix this I would review and consider.
