### ISSUE TITLE
Not able to debug .js test files

### ISSUE THREAD

**Issue by pallz12** [mmanela/chutzpah#809]
Hi,
I have downloaded both Chutzpah Test Explorer Adapter and Chutzpah Test Context menu and using VS Professional 2019 .
I am able to run .js test files and debug them on the Chrome browser via Chutzpah but am not able to debug them in VS.
Any suggestions?
Here is my chutzpah.json file:
{
  "BrowserArguments": {
    "chrome": "--allow-file-access-from-files --allow-file-access"
  },
  "Engine": "Chrome",
  "Framework": "jasmine",
  "FrameworkVersion": "3.5.0"

}

And here is my error:

Error: System.InvalidOperationException: Unable to debug the process: Visual Studio debugger not found.
at Chutzpah.VS.Common.DteHelpers.DebugAttachToProcess(Int32 subjectProcessId, String debugEngine)
at Chutzpah.VS.Common.VsDebuggerTestLauncher.LaunchTest(TestContext testContext)
at Chutzpah.TestRunner.<>c__DisplayClass39_0.<ExecuteTestContexts>b__0(TestContext testContext)

**Comment by KyleKolander** [comment]
I'm experiencing the same thing, being unable to debug, using Visual Studio Enterprise 2022 (64-bit) Version 17.1.0.  I have installed version 4.4.12 of both the [Chutzpah Test Context Menu 2022](https://marketplace.visualstudio.com/items?itemName=vs-publisher-2795.chutzpahcontextmenu2022) and [Chutzpah Test Explorer Adapter 2022](https://marketplace.visualstudio.com/items?itemName=vs-publisher-2795.chutzpahtestadapater2022) extensions.  In case it matters, I run Visual Studio as Administrator.

I can run the tests without issue, but can't debug.  I get the same error as @pallz12.  I looked through your code and can see the error is here: [Unable to debug the process: Visual Studio debugger not found](https://github.com/mmanela/chutzpah/blob/master/VS.Common/DteHelpers.cs#:~:text=Unable%20to%20debug%20the%20process%3A%20Visual%20Studio%20debugger%20not%20found).  Seems to be an issue with the DTE Interface.

I followed the steps on the [Debugging In Visual Studio](https://github.com/mmanela/chutzpah/wiki/Debugging-Unit-Tests#debugging-in-visual-studio) wiki page.  Note that I don't have Internet Explorer installed anymore, but Edge is installed, so there are still Internet Options (see below).  It looks like the wiki pages are out of date (last updated at least 5 or 6 years ago).  Could it be that I'm missing some configuration step(s) because I followed old documentation?

![image](https://user-images.githubusercontent.com/22461822/157870604-19d99757-1e2b-4aa1-84e9-1ebab2724762.png)

@mmanela - thank you for creating these extensions and updating them to work with Visual Studio 2022!  I'm sure you're really busy, but it would be very much appreciated if you could help figure out how to debug in Visual Studio.
