### ISSUE TITLE
VS2022 Extension Test Discovery Error

### ISSUE THREAD

**Issue by pfranceschi25** [mmanela/chutzpah#811]
I'm getting the following error during test discovery:

========== Starting test discovery ==========
Chutzpah Error: System.IO.FileNotFoundException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Diagnostics.DiagnosticSource, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Chutzpah.Server.ChutzpahWebServerFactory.BuildHost(String rootPath, Int32 defaultPort, String builtInDependencyFolder)
   at Chutzpah.Server.ChutzpahWebServerFactory.CreateServer(ChutzpahWebServerConfiguration configuration, IChutzpahWebServerHost activeWebServerHost)
   at Chutzpah.TestRunner.SetupWebServerHost(ConcurrentBag`1 testContexts, TestOptions options)
   at Chutzpah.TestRunner.ProcessTestPaths(IEnumerable`1 testPaths, TestOptions options, TestExecutionMode testExecutionMode, ITestMethodRunnerCallback callback, IChutzpahWebServerHost activeWebServerHost)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

An exception occurred while test discoverer 'ChutzpahTestDiscoverer' was loading tests. Exception: Could not load type 'Chutzpah.VS2012.TestAdapter.ChutzpahTracingHelper' from assembly 'Chutzpah.VS.Common, Version=4.4.12.0, Culture=neutral, PublicKeyToken=1ca802c37ffe1896'.
========== Test discovery finished: 0 Tests found in 1.8 sec ==========

I'm running a .NET Framework 4.8 project and jasmine 3.5.0 in VS 2022. Chutzpah nuget package version is also 4.0.12. The same proejct was previously working in VS2019, and Chutzpah v4.0.10.

Any help would be appreciated. Thanks for all you do!

**Comment by openHawkes** [comment]
I'm receiving the same issue after swapping to Visual Studio 2022 and using the new extension.

```
Building Test Projects
========== Starting test run ==========
Chutzpah Error: System.IO.FileNotFoundException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Diagnostics.DiagnosticSource, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Chutzpah.Server.ChutzpahWebServerFactory.BuildHost(String rootPath, Int32 defaultPort, String builtInDependencyFolder)
   at Chutzpah.Server.ChutzpahWebServerFactory.CreateServer(ChutzpahWebServerConfiguration configuration, IChutzpahWebServerHost activeWebServerHost)
   at Chutzpah.TestRunner.SetupWebServerHost(ConcurrentBag`1 testContexts, TestOptions options)
   at Chutzpah.TestRunner.ProcessTestPaths(IEnumerable`1 testPaths, TestOptions options, TestExecutionMode testExecutionMode, ITestMethodRunnerCallback callback, IChutzpahWebServerHost activeWebServerHost)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].



========== Test run finished: 0 Tests (0 Passed, 0 Failed, 0 Skipped) run in 241.4 ms ==========
```

I tried installing the nuget for DiagnosticsSource, though 4.0.3 isn't an option, only 4.0.0 (and higher versions), but still received the same error afterwards.

![nuget installation info](https://user-images.githubusercontent.com/104998366/219958122-fb7b8390-3f25-452b-a3bb-86dfb7ec868d.png)

When I use the Test Explorer to run tests, these are skipped. Some js tests _are_ run, however. Not sure what's up.

![chutzpah extension info](https://user-images.githubusercontent.com/104998366/219958232-b9362208-d9b0-407a-997e-20803e7f716b.png)

**Comment by supremedictator** [comment]
I am also receiving the same problem.

VS2022 Version 17.7.0
.Net 4.8 Project
Chutzpah Test Explorer Adapter v4.4.12

```
Error: System.InvalidOperationException: Process must exit before requested information can be determined.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_ExitCode()
   at Chutzpah.ProcessHelper.RunExecutableAndProcessOutput(String exePath, String arguments, Func`2 streamProcessor, Int32 streamTimeout, IDictionary`2 environmentVars)
   at Chutzpah.PhantomTestExecutionProvider.Execute(TestOptions testOptions, TestContext testContext, TestExecutionMode testExecutionMode, ITestMethodRunnerCallback callback)
   at Chutzpah.TestRunner.InvokeTestRunner(TestOptions options, TestContext testContext, TestExecutionMode testExecutionMode, ITestMethodRunnerCallback callback)
   at Chutzpah.TestRunner.<>c__DisplayClass39_0.<ExecuteTestContexts>b__0(TestContext testContext)
```

Has anyone been able to work around this?
